### ISSUE TITLE
Viser-ng does not work in the project that Angular-CLI created

### ISSUE THREAD

**Issue by SangKa** [viserjs/viser#11]
First will be the compile error:

![image](https://user-images.githubusercontent.com/6177271/33156285-55995894-d033-11e7-961b-37eb5b405558.png)

And figure out this, another compile error  emerge in the browser console:

![image](https://user-images.githubusercontent.com/6177271/33156288-5da94314-d033-11e7-9915-c4a74ca485d6.png)

Environment:

Windows 7
Node 8.9.0
Angular 5.0.2
Angular CLI  1.5.3

**Comment by arcthur** [comment]
It is a type of node problem, and I fixed already.
