### ISSUE TITLE
双轴图表的示例有没有

### ISSUE THREAD

**Issue by zhenglong0034** [viserjs/viser#116]
如何双轴图表？

**Comment by huxiaoyun** [comment]
// Viser 范例
// Viser Demo 平台: https://viserjs.github.io/demo.html

 import { View, Chart, Tooltip, Axis,Area, Line, Point } from 'viser-react';
 import * as ReactDOM from 'react-dom';
 import * as React from 'react';

  const data = [
    { time: 1246406400000, temperature: [ 14.3, 27.7 ], temperature1: 21.5 },
    { time: 1246492800000, temperature: [ 14.5, 27.8 ], temperature1: 21.5  },
    { time: 1246579200000, temperature: [ 15.5, 29.6 ], temperature1: 21.5  },
    { time: 1246665600000, temperature: [ 16.7, 30.7 ], temperature1: 21.5  },
    { time: 1246752000000, temperature: [ 16.5, 25.0 ], temperature1: 21.5  },
    { time: 1246838400000, temperature: [ 17.8, 25.7 ], temperature1: 21.5  },
    { time: 1246924800000, temperature: [ 13.5, 24.8 ], temperature1: 21.5  },
    { time: 1247011200000, temperature: [ 10.5, 21.4 ], temperature1: 21.5  },
    { time: 1247097600000, temperature: [ 9.2, 23.8 ], temperature1: 21.5  },
    { time: 1247184000000, temperature: [ 11.6, 21.8 ], temperature1: 21.5  },
  ];

 const scale = [{
   dataKey: 'temperature',
   sync: true
 },{
   dataKey: 'time',
   type: 'time',
   mask: 'MM-DD',
   tickInterval: 24 * 3600 * 1000 * 2
 }];

ReactDOM.render(
  <Chart forceFit height={400} scale={scale}>
    <Tooltip />
    <Axis position="right" dataKey="temperature"></Axis>
    <Axis position="left" dataKey="temperature1"></Axis>
    <View data={data} scale={scale}>
    	<Area position="time*temperature"></Area>
    </View>
    <View data={data}>
    	<Line position='time*temperature1'></Line>
    </View>
  </Chart>,
  mountNode
);

**Comment by huxiaoyun** [comment]
>   <Chart forceFit height={400} scale={scale}>
    <Tooltip />
    <Axis position="right" dataKey="temperature"></Axis>
    <Axis position="left" dataKey="temperature1"></Axis>
    <View data={data} scale={scale}>
    	<Area position="time*temperature"></Area>
    </View>
    <View data={data}>
    	<Line position='time*temperature1'></Line>
    </View>
  </Chart>

**Comment by huxiaoyun** [comment]
`<div>xx</div>`

**Comment by zhenglong0034** [comment]
ok, 3q
I will try

**Comment by evilucifero** [comment]
@zhenglong0034 If you find any inconvenience in using viser to create your own chart, just tell us here. You are welcome.

**Comment by ShawshankLin** [comment]
如果一个轴是两条，一个轴是一条线呢？

**Comment by ShawshankLin** [comment]
@huxiaoyun
