### ISSUE TITLE
umd直接引用不识别标签呢

### ISSUE THREAD

**Issue by xiaofeitu2** [viserjs/viser#131]
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title>vue-antv</title>
	<script src="viser-vue.min.js"></script>
	<script src="jquery-3.2.1.js"></script>
	<script src="vue.js"></script>
</head>
<body>
  <div id="app">
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip />
      <v-axis />
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>
  </div>
</body>
<script>
const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  min: 0,
  max: 1,
}];

var app={
  data() {
    return {
      data,
      scale,
      height: 400,
    };
  }
};
var Ctor = Vue.extend(app);
new Ctor().$mount('#app');

</script>

</html>
这样使用提示vue没识别标签，是怎么回事？

**Comment by evilucifero** [comment]
Can you provide a full version of your demo with well-indent format? I can not locate any problem with the information you given. Sorry.

**Comment by xiaofeitu2** [comment]
[viser.txt](https://github.com/viserjs/viser/files/1701569/viser.txt)

**Comment by onceing** [comment]
这样就可以了
[viser.txt](https://github.com/viserjs/viser/files/1840091/viser.txt)
