### ISSUE TITLE
`ng serve` to start angular web fails

### ISSUE THREAD

**Issue by fbchen** [viserjs/viser#135]
启动时报错，导致工程启动失败，错误信息如下：

<pre>
ERROR in node_modules/viser-ng/src/Chart.ts(345,11): error TS6133: 'views' is declared but never used.
node_modules/viser-ng/src/LiteChart.ts(4,10): error TS6133: 'generateRandomNum' is declared but never used.
node_modules/viser-ng/src/LiteChart.ts(214,11): error TS6133: 'name' is declared but never used.
node_modules/viser-ng/src/components/Legend.ts(2,10): error TS6133: 'NgModule' is declared but never used.
node_modules/viser-ng/src/plugins/Plugin.ts(1,36): error TS6133: 'Input' is declared but never used.
node_modules/viser-ng/src/plugins/Plugin.ts(1,69): error TS6133: 'ViewChild' is declared but never used.
node_modules/viser-ng/src/plugins/Plugin.ts(4,10): error TS6133: 'Slider' is declared but never used.
node_modules/viser-ng/src/plugins/Plugin.ts(34,11): error TS6133: 'realName' is declared but never used.
node_modules/viser-ng/src/plugins/Slider.ts(1,28): error TS6133: 'ViewContainerRef' is declared but never used.
node_modules/viser-ng/src/plugins/Slider.ts(3,10): error TS6133: 'PluginContext' is declared but never used.
node_modules/viser-ng/src/plugins/Slider.ts(5,10): error TS6133: 'generateRandomNum' is declared but never used.
node_modules/viser/src/core/CommonChart.ts(12,13): error TS6133: 'setCustomFormatter' is declared but never used.
node_modules/viser/src/core/CommonChart.ts(17,12): error TS2304: Cannot find name 'require'.
node_modules/viser/src/core/CommonChart.ts(18,15): error TS2304: Cannot find name 'require'.
node_modules/viser/src/index.ts(16,12): error TS2304: Cannot find name 'require'.
node_modules/viser/src/plugins/Slider.ts(1,7): error TS6133: 'G2' is declared but never used.
node_modules/viser/src/plugins/Slider.ts(1,12): error TS2304: Cannot find name 'require'.
node_modules/viser/src/plugins/Slider.ts(2,16): error TS2304: Cannot find name 'require'.
node_modules/viser/src/typed/ISeries.ts(1,13): error TS6133: 'IStyle' is declared but never used.
node_modules/viser/src/utils/CustomizeUtils.ts(1,12): error TS2304: Cannot find name 'require'.
</pre>

因项目需要，我们有硬性要求设置tslint.json，其中设置：
```
"no-unused-expression": true,
"no-unused-variable": true
```

请问，如何解决此问题？

**Comment by huxiaoyun** [comment]
请去除第三方的tslint 检测把

linterOptions?: { exclude?: string[] }
