### ISSUE TITLE
How to set legend's alias?

### ISSUE THREAD

**Issue by lanyulin** [viserjs/viser#136]
The fileds in Data are English, but i want to show Chinese on page.

**Comment by lanyulin** [comment]
I find the fucntion 'itemFormatter', but what's data type of this function's return value

**Comment by evilucifero** [comment]
Would you like to paste you code here?

**Comment by evilucifero** [comment]
I guess you want to display legend in Chinese but the original data's key is in English. Here is a recommend solution: just use Chinese as data key. Like below:

```javascript
// Before
[{ weight: 60 }, { weight: 50 }, { weight: 80 }]

// After
[{ 重量: 60 }, { 重量: 50 }, { 重量: 80 }]
```

**Comment by evilucifero** [comment]
You can just use DataSet's `transform` method to do such action.

**Comment by lanyulin** [comment]
ItemFormatter can solve this problem, but i think it's better to return a array which as fields' reflect. It looks like your suggestion is better. （开始以为itemFormatter返回数组，是和transform中（type: 'fold'）fields一一对应的，实际上是需要判断。因为Tooltip里也需要转换，所以还是采用你说的transform（type: 'map'））

<Legend itemFormatter={ (item) => {
    if(item == 'businessIncome') return '营业收入';
    else if(item == 'cardSellingIncome') return '售卡收入'
 }}/>

**Comment by evilucifero** [comment]
Yep, that's the point. Use formatter only affect in component's display, but the way use DataSet to do data pre-processing would affect the whole procedure to display a chart include a lot of internal logics like position calculation.
