### ISSUE TITLE
Jsx can't be transform into js.

### ISSUE THREAD

**Issue by lanyulin** [viserjs/viser#138]
I want to change the label in Pie and insert dom use jsx, it loos like can't transform into js.
`<Pie
              position="amt"
              color="name"
              style={{ stroke: '#fff', lineWidth: 1 }}
              label={['percent', {
                formatter: (val, item) => {
                  return (<div>
                      <p>{ item.point.name }</p>
                      <p><span>`￥${ item.point.amt } |`</span><span>{ val }</span></p>
                    </div>
                  )
                }
              }]}
            />`

Page shows [object Object].

**Comment by lanyulin** [comment]
``

**Comment by evilucifero** [comment]
We don't support directly use jsx in label property, you should use a template-like api to render your custom label.

Here is a demo.
https://viserjs.github.io/demo.html#/others/custom-label-pie

**Comment by lanyulin** [comment]
Thank you very much.
