### ISSUE TITLE
angular版本如何实现事件绑定

### ISSUE THREAD

**Issue by assertyang** [viserjs/viser#139]
`<v-point position="day*invqty" color="invtype" [size]="4" [style]="style" shape="circle" [onClick]="testclick()" ></v-point>
`
angular component中 testclick 模拟定义如下
` testclick= (ev, chart) => {
        
        console.log(this.ssssi++);
    }`
我在html模板中使用了这段代码，希望在折线图点击某个节点的时候执行一些动作，但是实际过程中，会导致testclick 重复执行N次。。找了demo和案例中没有类似说明，请问需要如何做呢？谢谢

**Comment by evilucifero** [comment]
It's weird. It should work fine.
Would you like to paste your full code here?

**Comment by taurusnail** [comment]
为什么angular版本不用angular的@output方式处理事件，viser文档中也没找到angular版本的事件绑定是如何编写，按@assertyang 的那种写法我也的确会出现控制台狂刷事件响应的log，而且还没拿到事件和chart的值，请问如何解决呢？有标准写法供参考吗？

**Comment by huxiaoyun** [comment]
mark...leave a demo here.

**Comment by channingwei** [comment]
我在省市区省市区下钻图中用了@ViewChild来绑定事件，目前效果还不错。倒是遇到了项目编译ng serve --prod会出错！
