### ISSUE TITLE
什么时候出文档啊

### ISSUE THREAD

**Issue by zhuss** [viserjs/viser#14]
没有文档，盲用啊，vue组件跟着你的demo用了还是很方便的，但是没有文档啊。

**Comment by arcthur** [comment]
文档得慢一些，主要补的是与 G2 的差异，大部分参数设定与 G2 是一样的，我这周会先把 demo 补上

**Comment by evilucifero** [comment]
Access the latest docs here: [Viser Docs](https://viserjs.github.io/docs.html)
Thanks for supporting viser.
