### ISSUE TITLE
桑基图的使用

### ISSUE THREAD

**Issue by ShawshankLin** [viserjs/viser#147]
桑基图可以鼠标滑动到关联线的时候显示动态效果吗，，，然后两边显示提示文字，，例如
![qq 20180313202742](https://user-images.githubusercontent.com/16248686/37341624-0e461ba0-26fd-11e8-8356-728cadb881cd.png)

**Comment by huxiaoyun** [comment]
这个估计要定制事件响应。我弄个demo 试试看。

**Comment by huxiaoyun** [comment]
动态效果是什么样？ 有可能需要自定义animation

**Comment by ShawshankLin** [comment]
http://mobile.umeng.com/apps/c160103c875c89df03381e35/wau/transition @huxiaoyun

**Comment by ShawshankLin** [comment]
@huxiaoyun 有消息吗?
