### ISSUE TITLE
How to omit some labels of x-axis?

### ISSUE THREAD

**Issue by lanyulin** [viserjs/viser#149]
![1](https://user-images.githubusercontent.com/13092461/37455688-a31110ec-2878-11e8-8a4f-7de0d35a7f1b.png)

**Comment by evilucifero** [comment]
You can use `ticks` or `tickCount` to limit count of axis' tick.

**Comment by evilucifero** [comment]
Here is a demo. https://viserjs.github.io/demo.html#/others/timeline-bubble

**Comment by lanyulin** [comment]
thank you
