### ISSUE TITLE
ng build --prod 编译后的文件不可用，访问无法正常绘制图表

### ISSUE THREAD

**Issue by hmukan** [viserjs/viser#151]
viser-ng版本：
编译后的文件部署到nginx服务后，访问无法正常绘制图表
 浏览器F12的Console中输出：ERROR TypeError: Cannot set property 'container' of undefined(…)

重现demo：https://github.com/linhuiw/viser-ng-demo

**Comment by arcthur** [comment]
2.2.4 fixed
