### ISSUE TITLE
多色仪表盘 鼠标在图表上移动会报错：Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by webliuxiang** [viserjs/viser#152]
viser-ng 版本的 guage 图表的多色仪表盘，当鼠标移到图表容器上的时候，控制台报错：
ERROR TypeError: Cannot read property 'get' of undefined
重现：https://viserjs.github.io/demo.html#/gauge/color-gauge
@linhuiw @ascoders

**Comment by webliuxiang** [comment]
文档也好少啊，

**Comment by webliuxiang** [comment]
@linhuiw @ascoders

**Comment by linhuiw** [comment]
OK, 收到. 我们这边改一下

**Comment by webliuxiang** [comment]
是什么原因导致的？修改完成后能告知一下吗？谢谢
