### ISSUE TITLE
文档很不完善

### ISSUE THREAD

**Issue by dingyiming** [viserjs/viser#154]
文档很不完善，是否有完善的筹划？

**Comment by huxiaoyun** [comment]
正在完善，请问下你最关注哪方面？

**Comment by YuJoycy** [comment]
ERROR in ./node_modules/viser-ng/src/Chart.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\Chart.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/chartService.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\chartService.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Axis.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\components\Axis.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Legend.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\components\Legend.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Series.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\components\Series.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Tooltip.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\components\Tooltip.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/module.ts
Module build failed: Error: D:\后台\frontend.ai\node_modules\viser-ng\src\module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\后台\frontend.ai\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/routes/dashboard/v1/v1.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/Chart.ngfactory' in 'D:\后台\frontend.ai\src\app\routes\dashboard\v1'
ERROR in ./src/app/routes/dashboard/v1/v1.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Axis.ngfactory' in 'D:\后台\frontend.ai\src\app\routes\dashboard\v1'
ERROR in ./src/app/routes/dashboard/v1/v1.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Legend.ngfactory' in 'D:\后台\frontend.ai\src\app\routes\dashboard\v1'
ERROR in ./src/app/routes/dashboard/v1/v1.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Series.ngfactory' in 'D:\后台\frontend.ai\src\app\routes\dashboard\v1'
ERROR in ./src/app/routes/dashboard/v1/v1.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Tooltip.ngfactory' in 'D:\后台\frontend.ai\src\app\routes\dashboard\v1'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/customer/customer.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/plan/plan.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/power/power.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/project/project.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/role/role.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy
Module not found: Error: Can't resolve 'D:/后台/frontend.ai/src/app/routes/user/user.module.ngfactory.js' in 'D:\后台\frontend.ai\src\$$_lazy_route_resource'
