### ISSUE TITLE
如何导出图片

### ISSUE THREAD

**Issue by Cuihongsen** [viserjs/viser#158]
在代码里有downloadImage的函数不知如何使用

**Comment by evilucifero** [comment]
Sorry, It seems that we don't have any feature like that. :-(

**Comment by Cuihongsen** [comment]
通过npm安装后会出现一个umd文件夹，里面是有定义downloadImage方法的

**Comment by huxiaoyun** [comment]
获取chart实例，可以  chart.downloadImage(name)    

(name: string)图表导出功能，通过传入 name 来指定下载图片的文件名。
