### ISSUE TITLE
在Vue里没有办法获得G2chart的引用

### ISSUE THREAD

**Issue by sgguo** [viserjs/viser#159]
考虑以下的代码

<v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip />
      <v-axis />
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>

如果直接在v-chart上添加vue的ref引用，得到的并不是G2的chart示例，从已有的文档中，也没有发现如何得到G2的chart实例

**Comment by huxiaoyun** [comment]
获取实例考虑下这样获取
`
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale" ref="chartComponent">
      <v-tooltip />
      <v-axis />
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>
  </div>
</template>

<script>
const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  min: 0,
  max: 1,
}];

export default {
  mounted() {
    console.log('hahahah', this.$refs.chartComponent.chart.chartInstance);
  },
  data() {
    return {
      data,
      scale,
      height: 400,
    };
  }
};
</script>


`

**Comment by sgguo** [comment]
多谢示例，今天测试一下。
