### ISSUE TITLE
热力图数据叠加

### ISSUE THREAD

**Issue by chusonglin** [viserjs/viser#162]
热力图需求： 
  1. 7天的数据 ， 30天的数据
  2. 切换时间区间，热力图跟随时间区间渲染

现在我选择七天的区间，绘制出七天的数据，再去选30天的时间区间，绘制出的热力图数据，是7天的数据和30天的数据的叠加 ！！！

请问这是什么原因造成的？？？？

**Comment by evilucifero** [comment]
Would you like to paste your demo here?

**Comment by dawiwt** [comment]
问题解决了么？
我现在遇到这种问题，如果更新react state，热力图会再次渲染，导致颜色加深
[https://codesandbox.io/embed/73pkmxmrnq](查看示例)
示例中，2秒更新一次state，每隔2秒会看到热力图一直在重复渲染

**Comment by huxiaoyun** [comment]
mark

**Comment by wuchugit** [comment]
可以试下给图加上key={Date.now()}

**Comment by dawiwt** [comment]
@wuchugit 在图表上加key确实可以，不过需要把animate设置为false，否则动画会反复执行，可以点击[查看示例](https://codesandbox.io/embed/73pkmxmrnq)
