### ISSUE TITLE
是否支持按需加载

### ISSUE THREAD

**Issue by Cuihongsen** [viserjs/viser#166]
安装后在node_modules 里面发现了es目录 ，我尝试使用babel-plugin-import ，但是他们貌似是不兼容的，
```JS
Module not found: Error: Can't resolve 'viser-react/es/chart' in '/path/src/components/Data/Chart'
```

**Comment by huxiaoyun** [comment]
按需加载viser 本身代码并不会减少多少js体积。
![image](https://user-images.githubusercontent.com/4345248/39349342-312b863e-4a2d-11e8-9aa3-819c84d04b2b.png)
