### ISSUE TITLE
更新viser出现日期是timeCat类型会渲染多一个空白图

### ISSUE THREAD

**Issue by ShawshankLin** [viserjs/viser#167]
const scale = [{
   dataKey: 'date',
   type: 'timeCat',
   alias: '日期'
 }]  类型设置了timeCat会出现绘制了两个图，，一个是空白图，，，原本是不会的啊

**Comment by evilucifero** [comment]
Would you like to paste your code and screenshot here?

**Comment by ShawshankLin** [comment]
<v-chart :force-fit="true" :height="height" :data="getData" :padding="padding" :scale="scale">
          <v-tooltip :crosshairs="{ type: 'line' }" />
          <v-axis dataKey="value" />
          <v-legend />
          <v-line position="date*value" :size="2" color="key" />
          <v-area position="date*value" color="key" opacity="0.05"/>
        </v-chart>

const scale = [{
dataKey: 'date',
type: 'timeCat',
alias: '日期'
}] 

之前是怎么配置的，，我的date是日期，格式是‘YYYY-MM-DD’,我用的是timeCat类型，但是今天发现渲染的时候多出了空白，，我用time也不行，，只能是改成了cat类型

**Comment by ShawshankLin** [comment]
@evilucifero ????

**Comment by huxiaoyun** [comment]
能给个完整的例子吗？包括 数据格式

**Comment by huxiaoyun** [comment]
`
<template>
  <div>
    <v-chart :force-fit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip :on-show="onTooltipShow" :on-hide="onTooltipHide" :on-change="onTooltipChange"></v-tooltip>
      <v-axis></v-axis>
      <v-stack-bar :position="'year*percent'" :color="'country'" :v-style="stackBarStyle"></v-stack-bar>
    </v-chart>
  </div>
</template>

<script>
const DataSet = require('@antv/data-set');

const ds = new DataSet();
const dv = ds.createView().source(data);

dv.transform({
  type: 'percent',
  field: 'value',
  dimension: 'country',
  groupBy: ['year'],
  as: 'percent'
});

const data = [
  { country: 'Europe', year: '1750', value: 163 },
  { country: 'Europe', year: '1800', value: 203 },
  { country: 'Europe', year: '1850', value: 276 },
  { country: 'Europe', year: '1900', value: 408 },
  { country: 'Europe', year: '1950', value: 547 },
  { country: 'Europe', year: '1999', value: 729 },
  { country: 'Europe', year: '2050', value: 628 },
  { country: 'Europe', year: '2100', value: 828 },
  { country: 'Asia', year: '1750', value: 502 },
  { country: 'Asia', year: '1800', value: 635 },
  { country: 'Asia', year: '1850', value: 809 },
  { country: 'Asia', year: '1900', value: 947 },
  { country: 'Asia', year: '1950', value: 1402 },
  { country: 'Asia', year: '1999', value: 3634 },
  { country: 'Asia', year: '2050', value: 5268 },
  { country: 'Asia', year: '2100', value: 7268 }
];

const scale = [{
  dataKey: 'percent',
  min: 0,
  formatter: '.2%',
}, {
  dataKey: 'year',
  type: 'timeCat',
  alias: '日期'
}];

export default {
  data() {
    return {
      data: dv.rows,
      scale,
      height: 400,
      stackBarStyle: {
        stroke: '#fff',
        lineWidth: 1
      },
    };
  }
};
</script>



`

**Comment by huxiaoyun** [comment]
if u still have any problem , leave a complate demo and capture a screenshot.   it will help me to find the bug quickly.
