### ISSUE TITLE
热力图缩放后，数据展示有问题

### ISSUE THREAD

**Issue by linhuiw** [viserjs/viser#169]
问题描述：
浏览器缩放的时候，热力图数据点显示位置有问题。

复现地址：
https://viserjs.github.io/demo.html#/heatmap/heatmap

附图：
![image](https://user-images.githubusercontent.com/722603/39041516-7b2a7ec4-44bb-11e8-8456-430a9d2fc45a.png)

**Comment by huxiaoyun** [comment]
issue 已提交至 https://github.com/antvis/g2/issues/604 ， 有进展随时更新。

**Comment by huxiaoyun** [comment]
已解决。

**Comment by linhuiw** [comment]
好的，谢谢。
