### ISSUE TITLE
tsconfig启用noUnusedLocals会报错

### ISSUE THREAD

**Issue by ppjjzz** [viserjs/viser#172]
代码中有很多导入但是没有引用的变量，还有许多在方法里声明但是没有用到的变量或常量

**Comment by arcthur** [comment]
已经修复了，都改成 strict 模式

**Comment by ppjjzz** [comment]
viser-ng更新到2.2.7还是会报错

**Comment by arcthur** [comment]
加上noUnusedLocals又发了一版, 2.2.8 可以了
