### ISSUE TITLE
组件怎么引入进去 ？

### ISSUE THREAD

**Issue by vasesen** [viserjs/viser#174]
[Vue warn]: Unknown custom element: <v-chart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
 我用 import {Chart} from 'viser-vue'     export default{ componnets:{Chart}} 都写了 还是上面报错

**Comment by evilucifero** [comment]
The way used in Vue is quiet different from React.
Most of time, we suggest use the way below.

```
import ViserVue from 'viser-vue';
Vue.use(ViserVue);
```
