### ISSUE TITLE
新项目迁移时install后代码报错：Uncaught TypeError: Cannot read property 'Chart' of undefined

### ISSUE THREAD

**Issue by wangkuan0818** [viserjs/viser#179]
![image](https://user-images.githubusercontent.com/19339164/40102307-b7237938-591c-11e8-9763-8c49120290d7.png)

**Comment by evilucifero** [comment]
We have noticed this problem. We will fixed it in next version. Thanks

**Comment by NuliNuli** [comment]
请问这个问题 解决了吗？怎么解决的 亲？跪求 我现在在整这个

**Comment by wangkuan0818** [comment]
@NuliNuli 我换了另外一个库😅

**Comment by huxiaoyun** [comment]
@evilucifero    这个问题解决了吗？？不知前因后果，解决了，就标个记哈~
