### ISSUE TITLE
ng版打包报错

### ISSUE THREAD

**Issue by ppjjzz** [viserjs/viser#181]
ERROR in ./node_modules/viser-ng/src/Chart.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\Chart.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/chartService.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\chartService.ts is missing from the TypeScript compilation. Please make sure it is in
your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Axis.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\components\Axis.ts is missing from the TypeScript compilation. Please make sure it is
in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Series.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\components\Series.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/components/Tooltip.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\components\Tooltip.ts is missing from the TypeScript compilation. Please make sure it
is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/viser-ng/src/module.ts
Module build failed: Error: d:\ad-platform-fe\yisike\node_modules\viser-ng\src\module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (d:\ad-platform-fe\yisike\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/view/routes/report/report.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/Chart.ngfactory' in 'd:\ad-platform-fe\yisike\src\app\view\routes\report'
ERROR in ./src/app/view/routes/report/report.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Axis.ngfactory' in 'd:\ad-platform-fe\yisike\src\app\view\routes\report'
ERROR in ./src/app/view/routes/report/report.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Series.ngfactory' in 'd:\ad-platform-fe\yisike\src\app\view\routes\report'
ERROR in ./src/app/view/routes/report/report.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/viser-ng/src/components/Tooltip.ngfactory' in 'd:\ad-platform-fe\yisike\src\app\view\routes\report'
error Command failed with exit code 1.

你们自己用angular-cli新建个项目然后npm下包装下就知道了，希望能尽快解决该问题

**Comment by huxiaoyun** [comment]
thank u for ur issues.

**Comment by huxiaoyun** [comment]
hello , 我用ng cli 创建了一个demo 项目， build 没有问题。 https://github.com/huxiaoyun/viser-demo/tree/master/ng

你能fork 这个仓库，并把你的配置提交下吗？

**Comment by ppjjzz** [comment]
@huxiaoyun 已经提交配置了，你们检查一下。希望尽快修复咯，谢谢

**Comment by channingwei** [comment]
@huxiaoyun 我也遇到了同样的问题，能帮忙查看下配置吗？https://github.com/channingwei/viser-ng-build-issue.git

**Comment by channingwei** [comment]
@huxiaoyun ng build没问题，ng build --prod会报错

**Comment by nightn** [comment]
我发现有一个解决这个问题的权宜办法，**修改 `src/tsconfig.app.json`，手动控制编译文件列表，将 viser-ng 中必要的 ts 文件添加进 include 里面**。然后我使用 `ng build --prod --aot` 可以打包成功（我的 ng-cli 的版本是 6.0.8）。
附上我对 `tsconfig.app.json` 的部分修改：
```json
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "../node_modules/viser-ng/**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../node_modules/viser-ng/**/**.ts"
  ]
```
