### ISSUE TITLE
viser-vue正确的使用姿势是什么

### ISSUE THREAD

**Issue by heke1994** [viserjs/viser#20]
``` javascript
import viserVue from 'viser-vue'
Vue.use(viserVue)
```
应该是这样用？ 这样编译会有一个warning
![image](https://user-images.githubusercontent.com/25653119/33522535-19e0a6dc-d82a-11e7-8a65-488c5c9c0f43.png)
而且直接把demo搬过来会有错误
![image](https://user-images.githubusercontent.com/25653119/33522541-3399f498-d82a-11e7-965a-f34f3755c648.png)

**Comment by heke1994** [comment]
希望使用文档能够快一些补充

**Comment by arcthur** [comment]
试下 1.1.1 版本，使用 API 和 G2 是一样的

**Comment by heke1994** [comment]
1.1.1能用了，有个小问题，如果我在这个组件里使用的数据data，从父元素传过来，第二次改变了数据，数据格式完全改变了，直接使用G2，我可能会修改position等配置然后重新render, 在这里我应该怎么处理好呢，我试了，直接改变data（如果数据格式没变是没问题的），如果格式变了修改position什么的没起到作用，不展示数据了

**Comment by arcthur** [comment]
发下 demo，可以用 jsfiddle 或 codepen，我看下代码

**Comment by evilucifero** [comment]
Now viser-vue has become quite easily to use. You can read the lastest version of demo and docs. Thanks for support viser.

**Comment by skywi** [comment]
I solved this problem by adding a space to zero before the date;
Eg. '20200229' -> '20200229'
Hope to fix this bug soon!

**Comment by skywi** [comment]
I solved this problem by adding a space to zero before the date;
Eg. '20200229' -> ' 20200229'
Hope to fix this bug soon!
