### ISSUE TITLE
在vue中如何进行Chart级别主题切换

### ISSUE THREAD

**Issue by zengqinglie** [viserjs/viser#200]
官方例子里是使用`theme: 'dark'`参数配置:

```
const chart2 = new G2.Chart({
    container: 'c2',
    forceFit: true,
    height: 250,
    theme: 'dark'
  });
```

我这样写好像并没有什么效果: 
```
<v-chart :forceFit="true" height="300" :data="data" :scale="scale" :theme="'dark'">
</v-chart>
```
请问应该怎么正确使用?

**Comment by evilucifero** [comment]
We don't support this feature right now. We will consider to add it in next version. Thank you.

**Comment by evilucifero** [comment]
We don't support this feature right now. We will consider to add it in next version. Thank you.

**Comment by huxiaoyun** [comment]
feature comming soon...

**Comment by huxiaoyun** [comment]
supported! use the lastest version .thank u
