### ISSUE TITLE
dataSource 再无数据的情况下会出现问题

### ISSUE THREAD

**Issue by JackieLs** [viserjs/viser#204]
```js
<Chart
  forceFit
  height={400}
  data={dataSource}
  scale={[{
    dataKey: 'total',
    formatter: value =>  `${value}ms`,
  }, {
    type: 'time',
    dataKey: 'timestamps',
    tickInterval: someInterval,
    formatter: value => moment(value).format('YYYY-MM-DD HH:mm:ss'),
  }]}>
  <Tooltip crosshairs={{ type: 'line' }} />
  <Axis />
  <Legend />
  <Line position="timestamps*totalTime" />
  <Point position="timestamps*totalTime" size={4} style={{ stroke: '#fff', lineWidth: 1 }} shape="circle"/>
</Chart>
```
问题描述：
1、如果 dataSource = [] ，那么在在第一次绘制的时候会出现不绘制的情况，即使设置了height：400也会造成塌陷，不得不在外层套个div。
2、如果一开始 dataSource.length != 0，第二次继续请求数据，dataSource.length = 0的情况下，会出现一些残留？
![image](https://user-images.githubusercontent.com/14228179/42752336-23bff156-8920-11e8-9bf8-623604b15c1a.png)
![image](https://user-images.githubusercontent.com/14228179/42752308-0e41aa72-8920-11e8-8bc4-3c6a439ecf6e.png)
期待结果：
比如给个 placeholder 暂无数据，或者直接留白，不希望出现错乱或者塌陷。

**Comment by huxiaoyun** [comment]
这个就对于图表的绘制范围有争论了，有些会说对数据的验证为空需要包含在图表内部，有些会说图表库只负责渲染。

我们会考虑支持数据为空的情况~

多谢~
