### ISSUE TITLE
how to change font-size in viser-vue

### ISSUE THREAD

**Issue by baoyn** [viserjs/viser#205]
I want to change the font-size,I didn't find the documents for it,please help me,thanks

**Comment by huxiaoyun** [comment]
which component ??  we usually use style to config font size

**Comment by baoyn** [comment]
thanks,I want to set the font-size of x-axis and y-axis
<template>
<div>
  <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
    <v-tooltip />
    <v-axis />
    <v-line position="year*value" :size="2" />
    <v-area position="year*value" />
  </v-chart>
</div>
</template>

**Comment by baoyn** [comment]
<template>
<div>
  <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
    <v-tooltip />
    <v-axis />
    <v-line position="year*value" :size="2" />
    <v-area position="year*value" />
  </v-chart>
</div>
</template>

I want to set the font-size of x-axis and y-axis

y-axis
--

**Comment by baoyn** [comment]
I use Basic Area in vue,I want to set the font-size of x-axis and y-axis

**Comment by huxiaoyun** [comment]
![image](https://user-images.githubusercontent.com/4345248/43135133-f5158476-8f76-11e8-8a7e-3507095dc56e.png)



```
const label = {
  textStyle: {
    textAlign: 'center', // 文本对齐方向，可取值为： start center end
    fill: '#404040', // 文本的颜色
    fontSize: '12', // 文本大小
    fontWeight: 'bold', // 文本粗细
    rotate: 30, 
    textBaseline: 'top' // 文本基准线，可取 top middle bottom，默认为middle
  }
};

const title = {
  autoRotate: {boolean}, // 是否需要自动旋转，默认为 true 
  offset: {number}, // 数值，设置坐标轴标题距离坐标轴线的距离
  // 设置标题的文本样式
  textStyle: {
    textAlign: 'center', // 文本对齐方向，可取值为： start middle end
    fill: '#404040', // 文本的颜色
    fontSize: '12', // 文本大小
    fontWeight: 'bold', // 文本粗细
    rotate: 30, // 文本旋转角度，以角度为单位，仅当 autoRotate 为 false 时生效
    textBaseline: 'top' // 文本基准线，可取 top middle bottom，默认为middle
  },
  position: 'start' // 标题的显示位置（相对于坐标轴线），可取值为 start center end
}
<v-axis :label={label} :title={title}></v-axis>

```

**Comment by calebeaires** [comment]
@huxiaoyun Is there a way to transform text with something like css wrap break-word, or use html on v-axis label?

**Comment by plqin-xiaohao** [comment]
目前仅发现能设置 : 设置坐标轴标题距离坐标轴线的距离 , 
假设想设置 `label` 距离左侧的距离应该如何配置 ?

![image](https://user-images.githubusercontent.com/41833007/51598714-12c4e000-1f39-11e9-8118-644c23749c91.png)

@huxiaoyun
