### ISSUE TITLE
Cant hide X Axis on the angular version

### ISSUE THREAD

**Issue by calebeaires** [viserjs/viser#207]
I have tried to control what is showed to user. I have tried to hide only the X Axis, but I had no success. [Here](viser/packages/viser-ng/src/components/Axis.ts) there is properties to do that, but is does not works.

```html
<div class="chart">
  <div *ngIf="showChart && !loading" [style.width]="'100%'">
    <v-chart [forceFit]="forceFit" padding="auto" [height]="localTask.grid.height - 55" [data]="data" [scale]="scale">
      <v-coord type="rect" direction="LB"></v-coord>
      <v-tooltip></v-tooltip>
      <v-axis [label]="false"></v-axis>
      <v-legend></v-legend>
      <v-bar [position]="position" [label]="labelConfig" [color]="color" [adjust]="adjust"></v-bar>
    </v-chart>
  </div>
</div>
```

**Comment by evilucifero** [comment]
You can control a specified axis when you assign the property 'dataKey' to axis component. I think the code may help you in this case.

```
<Axis dataKey="date" show={false} />
```

https://viserjs.github.io/demo.html#/others/polar-range-column
In the demo, the date axis is hidden by a similar code. 

Thanks for using Viser!
