### ISSUE TITLE
地下室砖 地图

### ISSUE THREAD

**Issue by MinHongwei** [viserjs/viser#208]
Syntax error: E:\ant\myworkvrsm\ifire-fe\src\appbase\components\Charts\MapProvice\index.js: Unexpected token, expected "," (25:30)

  23 |       $.getScript('https://webapi.amap.com/ui/1.0/main.js?v=1.0.11')).then(() => {
  24 |       // 调用高德 api 绘制底图以及获取 geo 数据
> 25 |       const map = new (window as any).AMap.Map('china', {
     |                               ^
  26 |         zoom: 4
  27 |       });
  28 |
TypeError: Cannot read property 'push' of undefined
c.JN
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.mapChanged
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.Ty
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.set
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.setMap
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.setOptions
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
c.C
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
new c
https://webapi.amap.com/maps?v=1.4.1&key=0d78256ea89beeb8c25d1cd047549d1f&_=1532503660181:21:183
DistrictExplorer._renderPolygon
http://webapi.amap.com/ui/1.0/ui/geo/DistrictExplorer.js?v=1.0.11&mt=ui&key=0d78256ea89beeb8c25d1cd047549d1f:1154:27
DistrictExplorer._renderMultiPolygon
http://webapi.amap.com/ui/1.0/ui/geo/DistrictExplorer.js?v=1.0.11&mt=ui&key=0d78256ea89beeb8c25d1cd047549d1f:1149:114
DistrictExplorer.renderFeature
http://webapi.amap.com/ui/1.0/ui/geo/DistrictExplorer.js?v=1.0.11&mt=ui&key=0d78256ea89beeb8c25d1cd047549d1f:1213:32
DistrictExplorer.renderSubFeatures
http://webapi.amap.com/ui/1.0/ui/geo/DistrictExplorer.js?v=1.0.11&mt=ui&key=0d78256ea89beeb8c25d1cd047549d1f:1228:35
App._this.renderAreaPolygons
E:/ant/myworkvrsm/ifire-fe/src/appbase/components/Charts/MapProvice/index.js:135
  132 | const { districtExplorer } = this.state;
  133 | const node = _.cloneDeep(areaNode);
  134 | districtExplorer.clearFeaturePolygons();
> 135 | districtExplorer.renderSubFeatures(node, function(feature, i) {
  136 |   const fillColor = colors[i % colors.length];
  137 |   const strokeColor = colors[colors.length - 1 - i % colors.length];
  138 | 
View compiled
App._this.refreshAreaNode
E:/ant/myworkvrsm/ifire-fe/src/appbase/components/Charts/MapProvice/index.js:72
  69 | refreshAreaNode = (areaNode) => {
  70 |   const { districtExplorer } = this.state;
  71 |   districtExplorer.setHoverFeature(null);
> 72 |   this.renderAreaPolygons(areaNode);
  73 | }
  74 | 
  75 | //å è½½åºå
View compiled
(anonymous function)
E:/ant/myworkvrsm/ifire-fe/src/appbase/components/Charts/MapProvice/index.js:179
  176 | }
  177 | window.currentAreaNode = areaNode;
  178 | self.setState({ currentAreaNode: areaNode });
> 179 | self.refreshAreaNode(areaNode);
  180 | if (callback) {
  181 |   callback(null, areaNode);
  182 | }
View compiled
DistrictExplorer.<anonymous>
E:/ant/myworkvrsm/ifire-fe/src/appbase/components/Charts/MapProvice/index.js:125
  122 |     self.setState({geoData: geoDataView, data: dvData, name});
  123 | 
  124 |     if (callback) {
> 125 |       callback(null, areaNode);
  126 |     }
  127 |   });
  128 | }
View compiled
▶ 24 stack frames were collapsed.

**Comment by huxiaoyun** [comment]
能写个riddle 例子吗？？
