### ISSUE TITLE
bar+line

### ISSUE THREAD

**Issue by zqzy** [viserjs/viser#209]
如果 是组合图标 改怎么配置

**Comment by huxiaoyun** [comment]
`

      <Chart forceFit height={400} padding={[20, 80, 50, 110]} data={data}>
        <Coord type="rect" direction="LB" />
        <Tooltip />
        <Legend />
        <Axis dataKey="profession" label={{ offset: 12 }} />
        <Bar position="profession*range" />
        <Line position="profession*range" />
      </Chart>
`

**Comment by huxiaoyun** [comment]
if line and bar has different data  , demo as follow
```
  <Chart forceFit height={400} padding={[20, 80, 50, 110]} data={data}>
    <Coord type="rect" direction="LB" />
    <Tooltip />
    <Legend />
    <Axis dataKey="profession" label={{ offset: 12 }} />
    <view data={data1}>
      <Bar position="profession*range" />
    </view>
    <view data={data2}>
      <Line position="profession*range" />
    </view>
  </Chart>

```

**Comment by ShawshankLin** [comment]
如果是同一个数据，，左轴是两条折线，右轴是另一条折线，这种也可以用方法2吗？
