### ISSUE TITLE
数据切换，导致point的鼠标点击事件重复被监听

### ISSUE THREAD

**Issue by Enginebeck** [viserjs/viser#211]
在数据切换之后可能由于onClick事件重复监听导致点击point的click事件多次被trigger
代码：
`                
<Chart forceFit height={600} data={this.state.data} scale={scale}>
       <Tooltip/>
        <Axis/>
         <SmoothLine position={'_id*count'}/>
         <Point onClick={this.changeTimestamp}
                      position={'_id*count'}
                      shape="circle"/>
</Chart>             
`
在点击point的时候，this.changeTimestamp函数执行了三次
![image](https://user-images.githubusercontent.com/9574537/43299623-707f1876-918d-11e8-9237-57612118203c.png)
pls have a look!

**Comment by kinghoo5201** [comment]
能否贴上changeTimestamp的具体源码，正常情况只会触发一次的

**Comment by huxiaoyun** [comment]
如有需求重新 open
