### ISSUE TITLE
Unknown custom element: <v-chart> 

### ISSUE THREAD

**Issue by shiny** [viserjs/viser#213]
通过 unpkg 加载 UMD 版本，使用 Vue 官网文档上默认的 Vue 使用方式，会有以下错误提示

![image](https://user-images.githubusercontent.com/117487/43354762-907237c4-9284-11e8-9af3-21d847f89e66.png)

Fiddle 现场： https://jsfiddle.net/x5twgske/3/
求教正确使用方式

**Comment by shiny** [comment]
使用 `Vue.use(ViserVue.default);` 则不会再报错了，但使用示例，canvas 一片空白： https://jsfiddle.net/x5twgske/5/

**Comment by huxiaoyun** [comment]
check again ~~ fixed

**Comment by xiaoyu10714024** [comment]
@huxiaoyun  I have the same issue.  What should I do to fix this error?  Thank you in advance.
![default](https://user-images.githubusercontent.com/28524358/47990364-4eae8d00-e122-11e8-898f-ae06dee145e5.png)

<template id = 'dashboard'>

  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip :showTitle="false" dataKey="item*percent" />
      <v-axis />
      <v-legend dataKey="item" />
      <v-pie position="percent" color="item" :v-style="pieStyle" :label="labelConfig" />
      <v-coord type="theta" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { item: '事例一', count: 40 },
    { item: '事例二', count: 21 },
    { item: '事例三', count: 17 },
    { item: '事例四', count: 13 },
    { item: '事例五', count: 9 }
  ];

  const scale = [{
    dataKey: 'percent',
    min: 0,
    formatter: '.0%',
  }];

  const dv = new DataSet.View().source(sourceData);
  dv.transform({
    type: 'percent',
    field: 'count',
    dimension: 'item',
    as: 'percent'
  });
  const data = dv.rows;

  export default {
    data() {
      return {
        data,
        scale,
        height: 400,
        pieStyle: {
          stroke: "#fff",
          lineWidth: 1
        },
        labelConfig: ['percent', {
          formatter: (val, item) => {
            return item.point.item + ': ' + val;
          }
        }],
      };
    }
  };
</script>

**Comment by jstdoit** [comment]
+1 oss is an evil in China...
