### ISSUE TITLE
G2的水波图如何实现

### ISSUE THREAD

**Issue by LaamGinghong** [viserjs/viser#219]

**Comment by huxiaoyun** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/liquid-fill-gauge.html   i will post a demo this week ..

**Comment by huxiaoyun** [comment]
https://viserjs.github.io/demo.html#/viser/others/liquid-fill-gauge      demo is here

**Comment by SentiyWhen** [comment]
水波图 官网的例子Vue的不显示了 不知道为啥

**Comment by luckYaoyao** [comment]
无法显示，显示NaN%，不晓得为啥

**Comment by gaozz1** [comment]
.data(
          {
            value: value || 0
          }
        )
