### ISSUE TITLE
Viser-ng does not work in the project that Angular-CLI created

### ISSUE THREAD

**Issue by tk231321** [viserjs/viser#22]
error :node_modules/viser/src/components/setSeriesConfig.ts (237,10): Property 'forEach' does not exist on type 'ISeriesConfig'.
  Property 'forEach' does not exist on type 'ISeries'.
TypeScript2.7.0

**Comment by linhuiw** [comment]
@tk231321 May be you have installed the old version viser-ng. 
Please update viser-ng to lastest version.
or you can reference the [viser-ng & angluar-cli demo project](https://github.com/linhuiw/viser-ng-demo).

**Comment by SangKa** [comment]
Maybe you can update the code in the README of viser-ng.
https://github.com/linhuiw/viser-ng-demo/blob/77049fc3d5a1c23635ddf158a21b8d5363486065/src/app/app.component.ts#L40-L45
