### ISSUE TITLE
slider plugin get error: Cannot add property container, object is not extensible

### ISSUE THREAD

**Issue by lidad** [viserjs/viser#221]
when i draw a slider, i get this error
![image](https://user-images.githubusercontent.com/11391332/44451409-46b47600-a626-11e8-9db8-cba7b4ccdfc1.png)
this is my code:
![image](https://user-images.githubusercontent.com/11391332/44451467-6d72ac80-a626-11e8-8165-844248f70056.png)

**Comment by huxiaoyun** [comment]
only slider , without chart ?

**Comment by huxiaoyun** [comment]
already fixed
