### ISSUE TITLE
如何手動呼叫forceFit()?

### ISSUE THREAD

**Issue by guyugg** [viserjs/viser#222]
[https://imgur.com/qX2fVcS](url)

當y-scroll-bar出現時，圖表不會自動force-fit
導致width仍然是未出現scroll-bar時的狀態，畫面超出範圍

**Comment by huxiaoyun** [comment]
can u give a demo in jsfiddle or riddle  ？？ Sorry,   https://imgur.com/qX2fVcS  is invalid ， i cannot see anything .

**Comment by huxiaoyun** [comment]
if u have any demo , reopen the issue.

**Comment by MiaoJianxue** [comment]
我也想问这个问题，viser怎么调用forceFit方法，我手动伸缩图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表宽度才会自适应变化
