### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by nicolascine** [viserjs/viser#223]
I'm interested on contribute to this library, solving bugs, adding new features or writting documentation, I don't see any guide to check how I can start. But, maybe the current mantainers could tell me for where to start?

I'm spanish/english speaker, I do not understand Chinese 👍 

Thanks!

**Comment by huxiaoyun** [comment]
thank u to consider to be a mantainers.  u can fork this repo and pull a merge request ~~
