### ISSUE TITLE
viser-ng中slider数据异步加载问题

### ISSUE THREAD

**Issue by yangchuanshui** [viserjs/viser#227]
G2中slider数据异步加载是通过数据加载完成后new Slider来生成slider,而在angular mvvm框架，view中v-slider标签在异步数据未加载时就已经生成了slider，数据加载完后slider配置项的数据不会更新，案例如下：
### HTML：
`<v-plugin>
      <v-slider width="auto" [height]="26" scales= "scales"
        [data]="originDv" [start]="start" [end]="end"
        [xAxis]="'gmtCreate'" [yAxis]="'value'"
        [backgroundChart]="{
          type: 'line'
        }"
        [onChange]="this.slideChange"
      ></v-slider>
    </v-plugin>`
### ts:
`ngOnInit() {
    // 初始化数据，显示正确
    this.originDv = [
      { gmtCreate: '2018-08-01', value: 1 },
      { gmtCreate: '2018-08-02', value: 2 },
      { gmtCreate: '2018-08-03', value: 3 },
      { gmtCreate: '2018-08-04', value: 4 },
      { gmtCreate: '2018-08-05', value: 5 },
      { gmtCreate: '2018-08-06', value: 6 },
    ];
    this.start = this.originDv[0].gmtCreate;
    this.end = this.originDv[this.originDv.length - 1].gmtCreate;
    // 异步加载，显示出错
    this.http.post('@base/point/data/comm/list').subscribe((res: any) => {
      this.originDv = [
        { gmtCreate: '2018-08-01', value: 1 },
        { gmtCreate: '2018-08-02', value: 2 },
        { gmtCreate: '2018-08-03', value: 3 },
        { gmtCreate: '2018-08-04', value: 4 },
        { gmtCreate: '2018-08-05', value: 5 },
        { gmtCreate: '2018-08-06', value: 6 },
      ];
      this.start = this.originDv[0].gmtCreate;
      this.end = this.originDv[this.originDv.length - 1].gmtCreate;
    });
  }`

**Comment by huxiaoyun** [comment]
mark , finding out why ... 
if someone is familiar to ng,   thank u to find a solution ...

**Comment by huxiaoyun** [comment]
viser-react  viser-vue already fixed  

viser-ng will fix later

**Comment by yangchuanshui** [comment]
thanks
