### ISSUE TITLE
有官方讨论群吗?

### ISSUE THREAD

**Issue by t496971418** [viserjs/viser#231]
有官方讨论群吗?

**Comment by huxiaoyun** [comment]
issue把。容易沉淀

**Comment by t496971418** [comment]
I'm very interested in this project, and I'm a developer of vue. I hope you'll come up with some more detailed documentation. I still have a lot of difficulties in using VISER in vue, including calls to G2 instances.

**Comment by wuchugit** [comment]
issue是不是太慢了，建个官方群吧

**Comment by huxiaoyun** [comment]
we  maintain this project on parttime,  we hope users to maintain together , highly recommend to fix problems by yourself and pull a merge request ..


if u are in alibaba, u can find me by  maoshen .. thank u
