### ISSUE TITLE
viser-vue 的point 标签未支持style 属性

### ISSUE THREAD

**Issue by huxiaoyun** [viserjs/viser#24]
`
  <v-chart :force-fit="true" :height="height" :data="averages" :scale="scale">
    <v-tooltip />
    <v-axis />
    <v-line :position="'time*temperature'" :size="2" />
    <v-point :position="'time*temperature'" :size="4" :style="pointStyle"/>
    <v-view :view-id="2" :data="data">
      <v-area :position="'time*temperature'" />
    </v-view>
  </v-chart>
`

**Comment by arcthur** [comment]
use v-style instead
