### ISSUE TITLE
viser-graph中基础graph，通过state重新设置数据，旧图没有消失，新旧图会重叠

### ISSUE THREAD

**Issue by wuchugit** [viserjs/viser#244]
import { Graph, Zoom } from 'viser-graph-react';
import * as React from 'react';

const data = {
  nodes: [{
    id: 'node1',
    x: 100,
    y: 200
  },{
    id: 'node2',
    x: 300,
    y: 200
  }],
  edges: [{
    id: 'edge1',
    target: 'node2',
    source: 'node1'
  }]
};

const graph = {
  width: 500,
  height: 500,
  fitView: 'cc',
  fitViewPadding: true,
  animate: true,
  type: 'graph',
  data,
  onClick: function(ev, graph) {
    console.log('click', ev, graph);
  }
};
const zoom = {
  min: 1,
  max: 10,
};

export default class App extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <Graph {...graph}>
          <Zoom {...zoom}/>
        </Graph>
      </div>
    );
  }
}

**Comment by wuchugit** [comment]
这是组件报的错误，是不是组件这段事件迭代了啊？前段时间用的好好的
Uncaught TypeError: Cannot read property 'getShapeObj' of undefined
    at index.js:37

**Comment by huxiaoyun** [comment]
i cannot reproduce the problem ...

viser-graph-react: 0.1.11
viser-graph : 0.1.9
g6: 2.1.3
```
import { Graph, Zoom } from '../../../packages/viser-graph-react/src';
import * as React from 'react';

const data1 = {
  nodes: [{
    id: 'node1',
    x: 100,
    y: 200
  },{
    id: 'node2',
    x: 300,
    y: 200
  }],
  edges: [{
    id: 'edge1',
    target: 'node2',
    source: 'node1'
  }]
};

const data2 = {
  nodes: [{
    id: 'node1',
    x: 200,
    y: 200
  },{
    id: 'node2',
    x: 300,
    y: 200
  },{
    id: 'node3',
    x: 400,
    y: 400
  }],
  edges: [{
    id: 'edge1',
    target: 'node2',
    source: 'node1'
  }]
};

const graph = {
  width: 500,
  height: 500,
  fitView: 'cc',
  fitViewPadding: true,
  animate: true,
  type: 'graph',
  onClick: function(ev, graph) {
    console.log('click', ev, graph);
  }
};
const zoom = {
  min: 1,
  max: 10,
};

export default class App extends React.Component {
  state = {
    data: data1
  };

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        data: data2,
      });
    }, 2000);
  }

  render() {
    return (<div>
      <Graph {...graph} data={this.state.data}>
        <Zoom {...zoom}/>
      </Graph>
    </div>);
  }
}


```

**Comment by huxiaoyun** [comment]
http://id.tudou.com/i/UNTUyNDI1MjU5Ng==/videos?spm=a2hzp.8244740.0.0
