### ISSUE TITLE
直方图tooltip数据类型为time时，无法显示，控制台报错

### ISSUE THREAD

**Issue by Eijx** [viserjs/viser#246]
报错信息：
Uncaught Error: Invalid Date in fecha.format
    at Object.o.format (VM1665 viser-react.min.js:1)
    at e.getText (VM1665 viser-react.min.js:1)
    at e.getTipTitle (VM1665 viser-react.min.js:1)
    at e.getTipItems (VM1665 viser-react.min.js:1)
    at VM1665 viser-react.min.js:1
    at Object.t.exports [as each] (VM1665 viser-react.min.js:1)
    at VM1665 viser-react.min.js:1
    at Object.t.exports [as each] (VM1665 viser-react.min.js:1)
    at VM1665 viser-react.min.js:1
    at Object.t.exports [as each] (VM1665 viser-react.min.js:1)

JS代码：
`import { Chart, Tooltip, Axis, Bar } from 'viser-react';
import * as React from 'react';
const DataSet = require('@antv/data-set');

const data = [{"time":[1537272000000,1537272060000],"count":5},{"time":[1537272060000,1537272120000],"count":15},{"time":[1537272120000,1537272180000],"count":28},{"time":[1537272180000,1537272240000],"count":15},{"time":[1537272240000,1537272300000],"count":15},{"time":[1537272300000,1537272360000],"count":15},{"time":[1537272360000,1537272420000],"count":15},{"time":[1537272420000,1537272480000],"count":15},{"time":[1537272480000,1537272540000],"count":15},{"time":[1537272540000,1537272600000],"count":15},{"time":[1537272600000,1537272660000],"count":15},{"time":[1537272660000,1537272720000],"count":15},{"time":[1537272720000,1537272780000],"count":15},{"time":[1537272780000,1537272840000],"count":15},{"time":[1537272840000,1537272900000],"count":15},{"time":[1537272900000,1537272960000],"count":80},{"time":[1537272960000,1537273020000],"count":2086},{"time":[1537273020000,1537273080000],"count":2101},{"time":[1537273080000,1537273140000],"count":2097},{"time":[1537273140000,1537273200000],"count":2082},{"time":[1537273200000,1537273260000],"count":2094},{"time":[1537273260000,1537273320000],"count":2154},{"time":[1537273320000,1537273380000],"count":2068},{"time":[1537273380000,1537273440000],"count":2059},{"time":[1537273440000,1537273500000],"count":2100},{"time":[1537273500000,1537273560000],"count":2183},{"time":[1537273560000,1537273620000],"count":2093},{"time":[1537273620000,1537273680000],"count":2090},{"time":[1537273680000,1537273740000],"count":2140},{"time":[1537273740000,1537273800000],"count":296},{"time":[1537273800000,1537273860000],"count":0},{"time":[1537273860000,1537273920000],"count":0},{"time":[1537273920000,1537273980000],"count":0},{"time":[1537273980000,1537274040000],"count":0},{"time":[1537274040000,1537274100000],"count":0},{"time":[1537274100000,1537274160000],"count":0},{"time":[1537274160000,1537274220000],"count":0},{"time":[1537274220000,1537274280000],"count":0},{"time":[1537274280000,1537274340000],"count":0},{"time":[1537274340000,1537274400000],"count":0},{"time":[1537274400000,1537274460000],"count":0},{"time":[1537274460000,1537274520000],"count":0},{"time":[1537274520000,1537274580000],"count":0},{"time":[1537274580000,1537274640000],"count":0},{"time":[1537274640000,1537274700000],"count":0},{"time":[1537274700000,1537274760000],"count":0},{"time":[1537274760000,1537274820000],"count":0},{"time":[1537274820000,1537274880000],"count":0},{"time":[1537274880000,1537274940000],"count":0},{"time":[1537274940000,1537275000000],"count":0},{"time":[1537275000000,1537275060000],"count":0},{"time":[1537275060000,1537275120000],"count":0},{"time":[1537275120000,1537275180000],"count":0},{"time":[1537275180000,1537275240000],"count":0},{"time":[1537275240000,1537275300000],"count":0},{"time":[1537275300000,1537275360000],"count":0},{"time":[1537275360000,1537275420000],"count":0},{"time":[1537275420000,1537275480000],"count":0},{"time":[1537275480000,1537275540000],"count":0},{"time":[1537275540000,1537275600000],"count":0}]

const scale = [{
  dataKey: 'time',
  type:'time',
  mask:'HH:mm',
  nice: true,
}, {
  dataKey: 'count',
}];

export default class App extends React.Component {
  render() {
    return (
      <Chart forceFit height={400} data={data} scale={scale}>
        <Tooltip />
        <Axis />
        <Bar position="time*count" />
      </Chart>
    );
  }
}`

麻烦指点。。

**Comment by Eijx** [comment]
[
![283c8e75-f446-4748-be5e-f407d9b89428](https://user-images.githubusercontent.com/34332645/46070135-9fd87200-c1af-11e8-976a-8286701e1f94.png)
](url)
错误就是从这个地方抛出来的

**Comment by huxiaoyun** [comment]
同款娘口三三的头像。哈哈！！ mark 这个问题我来解决。

**Comment by huxiaoyun** [comment]
i make a demo ， can not find any problem 

```
import { Chart, Tooltip, Axis, Bar } from 'viser-react';
import * as React from 'react';
const DataSet = require('@antv/data-set');

const data = [{"time":[1537272000000,1537272060000],"count":5},{"time":[1537272060000,1537272120000],"count":15},{"time":[1537272120000,1537272180000],"count":28},{"time":[1537272180000,1537272240000],"count":15},{"time":[1537272240000,1537272300000],"count":15},{"time":[1537272300000,1537272360000],"count":15},{"time":[1537272360000,1537272420000],"count":15},{"time":[1537272420000,1537272480000],"count":15},{"time":[1537272480000,1537272540000],"count":15},{"time":[1537272540000,1537272600000],"count":15},{"time":[1537272600000,1537272660000],"count":15},{"time":[1537272660000,1537272720000],"count":15},{"time":[1537272720000,1537272780000],"count":15},{"time":[1537272780000,1537272840000],"count":15},{"time":[1537272840000,1537272900000],"count":15},{"time":[1537272900000,1537272960000],"count":80},{"time":[1537272960000,1537273020000],"count":2086},{"time":[1537273020000,1537273080000],"count":2101},{"time":[1537273080000,1537273140000],"count":2097},{"time":[1537273140000,1537273200000],"count":2082},{"time":[1537273200000,1537273260000],"count":2094},{"time":[1537273260000,1537273320000],"count":2154},{"time":[1537273320000,1537273380000],"count":2068},{"time":[1537273380000,1537273440000],"count":2059},{"time":[1537273440000,1537273500000],"count":2100},{"time":[1537273500000,1537273560000],"count":2183},{"time":[1537273560000,1537273620000],"count":2093},{"time":[1537273620000,1537273680000],"count":2090},{"time":[1537273680000,1537273740000],"count":2140},{"time":[1537273740000,1537273800000],"count":296},{"time":[1537273800000,1537273860000],"count":0},{"time":[1537273860000,1537273920000],"count":0},{"time":[1537273920000,1537273980000],"count":0},{"time":[1537273980000,1537274040000],"count":0},{"time":[1537274040000,1537274100000],"count":0},{"time":[1537274100000,1537274160000],"count":0},{"time":[1537274160000,1537274220000],"count":0},{"time":[1537274220000,1537274280000],"count":0},{"time":[1537274280000,1537274340000],"count":0},{"time":[1537274340000,1537274400000],"count":0},{"time":[1537274400000,1537274460000],"count":0},{"time":[1537274460000,1537274520000],"count":0},{"time":[1537274520000,1537274580000],"count":0},{"time":[1537274580000,1537274640000],"count":0},{"time":[1537274640000,1537274700000],"count":0},{"time":[1537274700000,1537274760000],"count":0},{"time":[1537274760000,1537274820000],"count":0},{"time":[1537274820000,1537274880000],"count":0},{"time":[1537274880000,1537274940000],"count":0},{"time":[1537274940000,1537275000000],"count":0},{"time":[1537275000000,1537275060000],"count":0},{"time":[1537275060000,1537275120000],"count":0},{"time":[1537275120000,1537275180000],"count":0},{"time":[1537275180000,1537275240000],"count":0},{"time":[1537275240000,1537275300000],"count":0},{"time":[1537275300000,1537275360000],"count":0},{"time":[1537275360000,1537275420000],"count":0},{"time":[1537275420000,1537275480000],"count":0},{"time":[1537275480000,1537275540000],"count":0},{"time":[1537275540000,1537275600000],"count":0}]

const scale = [{
  dataKey: 'time',
  type:'time',
  mask:'HH:mm',
  nice: true,
}, {
  dataKey: 'count',
}];

export default class App extends React.Component {
  render() {
    const formatter = val => {
      if ((val % 2)) {
       return val;
      }
      return '';
    };

    return (
      <Chart forceFit height={400} data={data} scale={scale}>
        <Tooltip crosshairs={false} inPlot={false} position="top" />
        <Axis dataKey="count"  />
        <Bar position="time*count" />
      </Chart>
    );
  }
}

```

![image](https://user-images.githubusercontent.com/4345248/46243809-43bd5a00-c40a-11e8-8efb-845c49a6bddf.png)

**Comment by Eijx** [comment]
> i make a demo ， can not find any problem
> 
> ```
> import { Chart, Tooltip, Axis, Bar } from 'viser-react';
> import * as React from 'react';
> const DataSet = require('@antv/data-set');
> 
> const data = [{"time":[1537272000000,1537272060000],"count":5},{"time":[1537272060000,1537272120000],"count":15},{"time":[1537272120000,1537272180000],"count":28},{"time":[1537272180000,1537272240000],"count":15},{"time":[1537272240000,1537272300000],"count":15},{"time":[1537272300000,1537272360000],"count":15},{"time":[1537272360000,1537272420000],"count":15},{"time":[1537272420000,1537272480000],"count":15},{"time":[1537272480000,1537272540000],"count":15},{"time":[1537272540000,1537272600000],"count":15},{"time":[1537272600000,1537272660000],"count":15},{"time":[1537272660000,1537272720000],"count":15},{"time":[1537272720000,1537272780000],"count":15},{"time":[1537272780000,1537272840000],"count":15},{"time":[1537272840000,1537272900000],"count":15},{"time":[1537272900000,1537272960000],"count":80},{"time":[1537272960000,1537273020000],"count":2086},{"time":[1537273020000,1537273080000],"count":2101},{"time":[1537273080000,1537273140000],"count":2097},{"time":[1537273140000,1537273200000],"count":2082},{"time":[1537273200000,1537273260000],"count":2094},{"time":[1537273260000,1537273320000],"count":2154},{"time":[1537273320000,1537273380000],"count":2068},{"time":[1537273380000,1537273440000],"count":2059},{"time":[1537273440000,1537273500000],"count":2100},{"time":[1537273500000,1537273560000],"count":2183},{"time":[1537273560000,1537273620000],"count":2093},{"time":[1537273620000,1537273680000],"count":2090},{"time":[1537273680000,1537273740000],"count":2140},{"time":[1537273740000,1537273800000],"count":296},{"time":[1537273800000,1537273860000],"count":0},{"time":[1537273860000,1537273920000],"count":0},{"time":[1537273920000,1537273980000],"count":0},{"time":[1537273980000,1537274040000],"count":0},{"time":[1537274040000,1537274100000],"count":0},{"time":[1537274100000,1537274160000],"count":0},{"time":[1537274160000,1537274220000],"count":0},{"time":[1537274220000,1537274280000],"count":0},{"time":[1537274280000,1537274340000],"count":0},{"time":[1537274340000,1537274400000],"count":0},{"time":[1537274400000,1537274460000],"count":0},{"time":[1537274460000,1537274520000],"count":0},{"time":[1537274520000,1537274580000],"count":0},{"time":[1537274580000,1537274640000],"count":0},{"time":[1537274640000,1537274700000],"count":0},{"time":[1537274700000,1537274760000],"count":0},{"time":[1537274760000,1537274820000],"count":0},{"time":[1537274820000,1537274880000],"count":0},{"time":[1537274880000,1537274940000],"count":0},{"time":[1537274940000,1537275000000],"count":0},{"time":[1537275000000,1537275060000],"count":0},{"time":[1537275060000,1537275120000],"count":0},{"time":[1537275120000,1537275180000],"count":0},{"time":[1537275180000,1537275240000],"count":0},{"time":[1537275240000,1537275300000],"count":0},{"time":[1537275300000,1537275360000],"count":0},{"time":[1537275360000,1537275420000],"count":0},{"time":[1537275420000,1537275480000],"count":0},{"time":[1537275480000,1537275540000],"count":0},{"time":[1537275540000,1537275600000],"count":0}]
> 
> const scale = [{
>   dataKey: 'time',
>   type:'time',
>   mask:'HH:mm',
>   nice: true,
> }, {
>   dataKey: 'count',
> }];
> 
> export default class App extends React.Component {
>   render() {
>     const formatter = val => {
>       if ((val % 2)) {
>        return val;
>       }
>       return '';
>     };
> 
>     return (
>       <Chart forceFit height={400} data={data} scale={scale}>
>         <Tooltip crosshairs={false} inPlot={false} position="top" />
>         <Axis dataKey="count"  />
>         <Bar position="time*count" />
>       </Chart>
>     );
>   }
> }
> ```
> ![image](https://user-images.githubusercontent.com/4345248/46243809-43bd5a00-c40a-11e8-8efb-845c49a6bddf.png)

图表可以出来，但是鼠标移动到图表上时tooltip展示不出来。。

**Comment by huxiaoyun** [comment]
```
import { Chart, Tooltip, Axis, Bar } from 'viser-react';
import * as React from 'react';
const DataSet = require('@antv/data-set');

const data = [{"time":[1537272000000,1537272060000],"count":5},{"time":[1537272060000,1537272120000],"count":15},{"time":[1537272120000,1537272180000],"count":28},{"time":[1537272180000,1537272240000],"count":15},{"time":[1537272240000,1537272300000],"count":15},{"time":[1537272300000,1537272360000],"count":15},{"time":[1537272360000,1537272420000],"count":15},{"time":[1537272420000,1537272480000],"count":15},{"time":[1537272480000,1537272540000],"count":15},{"time":[1537272540000,1537272600000],"count":15},{"time":[1537272600000,1537272660000],"count":15},{"time":[1537272660000,1537272720000],"count":15},{"time":[1537272720000,1537272780000],"count":15},{"time":[1537272780000,1537272840000],"count":15},{"time":[1537272840000,1537272900000],"count":15},{"time":[1537272900000,1537272960000],"count":80},{"time":[1537272960000,1537273020000],"count":2086},{"time":[1537273020000,1537273080000],"count":2101},{"time":[1537273080000,1537273140000],"count":2097},{"time":[1537273140000,1537273200000],"count":2082},{"time":[1537273200000,1537273260000],"count":2094},{"time":[1537273260000,1537273320000],"count":2154},{"time":[1537273320000,1537273380000],"count":2068},{"time":[1537273380000,1537273440000],"count":2059},{"time":[1537273440000,1537273500000],"count":2100},{"time":[1537273500000,1537273560000],"count":2183},{"time":[1537273560000,1537273620000],"count":2093},{"time":[1537273620000,1537273680000],"count":2090},{"time":[1537273680000,1537273740000],"count":2140},{"time":[1537273740000,1537273800000],"count":296},{"time":[1537273800000,1537273860000],"count":0},{"time":[1537273860000,1537273920000],"count":0},{"time":[1537273920000,1537273980000],"count":0},{"time":[1537273980000,1537274040000],"count":0},{"time":[1537274040000,1537274100000],"count":0},{"time":[1537274100000,1537274160000],"count":0},{"time":[1537274160000,1537274220000],"count":0},{"time":[1537274220000,1537274280000],"count":0},{"time":[1537274280000,1537274340000],"count":0},{"time":[1537274340000,1537274400000],"count":0},{"time":[1537274400000,1537274460000],"count":0},{"time":[1537274460000,1537274520000],"count":0},{"time":[1537274520000,1537274580000],"count":0},{"time":[1537274580000,1537274640000],"count":0},{"time":[1537274640000,1537274700000],"count":0},{"time":[1537274700000,1537274760000],"count":0},{"time":[1537274760000,1537274820000],"count":0},{"time":[1537274820000,1537274880000],"count":0},{"time":[1537274880000,1537274940000],"count":0},{"time":[1537274940000,1537275000000],"count":0},{"time":[1537275000000,1537275060000],"count":0},{"time":[1537275060000,1537275120000],"count":0},{"time":[1537275120000,1537275180000],"count":0},{"time":[1537275180000,1537275240000],"count":0},{"time":[1537275240000,1537275300000],"count":0},{"time":[1537275300000,1537275360000],"count":0},{"time":[1537275360000,1537275420000],"count":0},{"time":[1537275420000,1537275480000],"count":0},{"time":[1537275480000,1537275540000],"count":0},{"time":[1537275540000,1537275600000],"count":0}]

const scale = [{
  dataKey: 'time',
  //type:'time',
  //mask:'HH:mm',
  nice: true,
}, {
  dataKey: 'count',
}];

export default class App extends React.Component {
  render() {
    const formatter = val => {
      if ((val % 2)) {
       return val;
      }
      return '';
    };

    return (
      <Chart forceFit height={400} data={data} scale={scale}>
        <Tooltip />
        <Axis dataKey="time"  label={{
            formatter:(a) => {
                console.log('a', a);
                // format here
                return 'xx'
            }
        }}/>
        <Axis dataKey="count"  />
        <Bar position="time*count" tooltip={'count'}/>
      </Chart>
    );
  }
}

```
