### ISSUE TITLE
Bug折线图会超出一条直线

### ISSUE THREAD

**Issue by xld1393679430** [viserjs/viser#248]
![image](https://user-images.githubusercontent.com/22445609/46591493-a8a14000-caed-11e8-9323-64db4b5aa361.png)
![image](https://user-images.githubusercontent.com/22445609/46591511-d4242a80-caed-11e8-95cc-1e5e8b49f021.png)

**Comment by arcthur** [comment]
这个问题报到 G2 issue 上，关联这个 issue

**Comment by huxiaoyun** [comment]
g2 already fixed ~
latest version  g2 3.3.4
