### ISSUE TITLE
demo (极坐标弧长链接图) for Vue 出错

### ISSUE THREAD

**Issue by ssthouse** [viserjs/viser#249]
demo链接:
https://viserjs.github.io/demo.html#/viser/relation/arc-polar-diagram

React 效果:
![selection_438](https://user-images.githubusercontent.com/10973821/46593732-de035900-cb00-11e8-8b8c-a9f9c46bfa77.png)

Vue 效果:
![selection_437](https://user-images.githubusercontent.com/10973821/46593738-e360a380-cb00-11e8-94b2-2eb214579feb.png)

**Comment by jany3534** [comment]
有结论没？
