### ISSUE TITLE
viser-ng 的view 一定要分开编写，与 react , vue 的存在默认view 的形式不同

### ISSUE THREAD

**Issue by huxiaoyun** [viserjs/viser#25]
react
`      <Chart forceFit height={400} data={averages} scale={scale}>
        <Tooltip />
        <Axis />
        <Line position="time*temperature" size="2" />
        <Point position="time*temperature" size="4" style={pointStyle}/>
        <View viewId="2" data={data}>
          <Area position="time*temperature" />
        </View>
      </Chart>`

angular
`
    <Chart [forceFit]="forceFit" [height]="height">
      <View viewId="1" [data]="averages" [scale]="scale">
        <Tooltip></Tooltip>
        <Axis></Axis>
        <Line position="time*temperature" size="2"></Line>
        <Point position="time*temperature" size="4" [style]="pointStyle"></Point>
      </View>
      <View viewId="2" [data]="data"  [scale]="scale">
        <Area position="time*temperature" />
      </View>
    </Chart>
`
详情可见： https://viserjs.github.io/demo.html?type=area&example=4

**Comment by linhuiw** [comment]
这个是 angular 版本的预发差异, 这种差异没办法抹平.
