### ISSUE TITLE
viser-graph基础graph,通过state重新设置数据会出现图重叠和报错

### ISSUE THREAD

**Issue by wuchugit** [viserjs/viser#252]
![image](https://user-images.githubusercontent.com/12814008/47067526-41396d80-d21c-11e8-899d-81d78aed183f.png)
![image](https://user-images.githubusercontent.com/12814008/47067576-66c67700-d21c-11e8-9194-a06fc8c6e2ef.png)
![image](https://user-images.githubusercontent.com/12814008/47067593-7cd43780-d21c-11e8-8d31-308cedc53516.png)

**Comment by kinghoo5201** [comment]
给Chart组件添加key={Date.now()}强制让其重绘试试会不会出现重叠
