### ISSUE TITLE
ng-viser should run render outside of Angular

### ISSUE THREAD

**Issue by tonny008** [viserjs/viser#253]
g2 chart requests animation frame which cause Angular runs change detection. this will cause high cpu usage.

the chart render function should called outside Angular.

```
this.ngZone.runOutsideAngular(() => {
      chart.render();
    });
```

**Comment by tonny008** [comment]
https://stackblitz.com/edit/angular-ng-viser-changedetection
mousemove  on the first chart will not trigger change detection. but on the second chart will

**Comment by huxiaoyun** [comment]
can u pull a mr to fix this problem ~~
