### ISSUE TITLE
tooltip如何显示指定列显示单位

### ISSUE THREAD

**Issue by t880216t** [viserjs/viser#258]
您好，如图我需要给tooltip显示一个单位，请问怎么才能实现呢？

![20181031115519](https://user-images.githubusercontent.com/16489708/47765280-2d096c00-dd04-11e8-8798-8d8262d6c18e.png)

源数据如下：
`const sourceData = [
  { month: 'Jan', mem: 3.9 ,activity:'com.buyer'},]`

我有尝试，用itemTpl
` 
const itemTpl = '<li><span style="background-color:{color};width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>{name} : {value} mb</li>'

...
<Tooltip itemTpl={itemTpl} 
`
但这样下面的纯文本后面也会有这个mb,求教求教！

**Comment by huxiaoyun** [comment]
u can custom tooltip,  https://viserjs.github.io/demo.html#/viser/others/cutomize-tooltip



itemTpl will effect every line of tooltip

**Comment by SaberInoryKiss** [comment]
@t880216t 请问你后面解决了么，单独给某一行设置单位
