### ISSUE TITLE
angular环境下怎么控制point和line的绘制顺序，现在线上的点有时在上面有时在下面

### ISSUE THREAD

**Issue by XiaolinQian** [viserjs/viser#260]
<v-chart *ngIf="data.length > 0 " [id]="'panelsChart'" [height]="height" [data]="data" [scale]="scale" [width]="width" [padding]="[20, 40, 80, 60]">
  <v-tooltip></v-tooltip>  
    
  <v-axis dataKey="value" [label]="label" [grid]="null"></v-axis>
  <v-axis dataKey="time" [label]="label"></v-axis>
  
  <v-smooth-line position="time*value" appLayer shape="smooth"></v-smooth-line>
  <v-guide [type]="guideOpts.type" [top]="guideOpts.top" [start]="guideOpts.start" [end]="guideOpts.end" [lineStyle]="guideOpts.lineStyle"
    [text]="guideOpts.text"></v-guide>
  <v-guide [type]="guideOpts2.type" [top]="guideOpts2.top" [start]="guideOpts2.start" [end]="guideOpts2.end" [lineStyle]="guideOpts2.lineStyle"
    [text]="guideOpts2.text"></v-guide>
    
  <v-point position="time*value" [size]="pointSize" [style]="pointStyle" [shape]="pointShape" [color]="pointColor"></v-point>
</v-chart>

**Comment by XiaolinQian** [comment]
![image](https://user-images.githubusercontent.com/34698631/47905050-12c8bd00-dec1-11e8-9040-b5b9cd9ff1ff.png)
![image](https://user-images.githubusercontent.com/34698631/47905065-1eb47f00-dec1-11e8-98a3-e3bc7c825fc3.png)

**Comment by huxiaoyun** [comment]
根据你配置的顺序, 如下先绘制line  再绘制 point
```
  <div>
    <v-chart [forceFit]="forceFit" [height]="height" [data]="data" [scale]="scale">
      <v-tooltip></v-tooltip>
      <v-axis></v-axis>
      <v-line position="year*value"></v-line>
      <v-point position="year*value" shape="circle"></v-point>
    </v-chart>
  </div>
```
![image](https://user-images.githubusercontent.com/4345248/48176905-41291b00-e34d-11e8-8d77-c02911ebd023.png)


```
  <div>
    <v-chart [forceFit]="forceFit" [height]="height" [data]="data" [scale]="scale">
      <v-tooltip></v-tooltip>
      <v-axis></v-axis>
      <v-point position="year*value" shape="circle"></v-point>
      <v-line position="year*value"></v-line>
    </v-chart>
  </div>
```
先绘制 point 再绘制 line
![image](https://user-images.githubusercontent.com/4345248/48176931-5736db80-e34d-11e8-84ce-2f238e4db668.png)
