### ISSUE TITLE
只有一条数据时词云展示异常

### ISSUE THREAD

**Issue by zqian11** [viserjs/viser#265]
截取自官网demo实例部分，略做修改
`mounted() {
    $.getJSON('/assets/data/world-population.json', (data) => {
    // 此处demo为data中数据的片段，当数组中对象数量大于1个时正常显示，只有一个时无任何数据
      let demo = [
          {x: "China", value: 1383220000, category: "asia"}
    ];
      const dv = new DataSet.View().source(demo);
      const range = dv.range('value');
      const min = range[0];
      const max = range[1];
      dv.transform({
        type: 'tag-cloud',
        fields: ['x', 'value'],
        size: [640, 400],
        font: 'Verdana',
        padding: 0,
        timeInterval: 5000, // max execute time
        rotate() {
          let random = ~~(Math.random() * 4) % 4;
          if (random == 2) {
            random = 0;
          }
          return random * 90; // 0, 90, 270
        },
        fontSize(d) {
          if (d.value) {
            return ((d.value - min) / (max - min)) * (80 - 24) + 24;
          }
          return 0;
        }
      });
      this.$data.data = dv.rows;
    });
  },`

**Comment by kinghoo5201** [comment]
你尝试修改DataSet中transform的size的大小，如果限定过小了，dataSet会自动删减数据的，https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html，最好是用window的宽高，然后在fontSize用公式调整字体大小，希望能对你有用！

**Comment by zqian11** [comment]
> 你尝试修改DataSet中transform的size的大小，如果限定过小了，dataSet会自动删减数据的，https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html
> ，最好是用window的宽高，然后在fontSize用公式调整字体大小，希望能对你有用！

非常感谢回复。我输出了字号大小发现果然有问题，已经解决！
