### ISSUE TITLE
angular版本的文档

### ISSUE THREAD

**Issue by chenhongbinjs** [viserjs/viser#266]
请问哪里有angular版本的文档？angular的指令也没发现哪里有介绍怎么使用？

**Comment by chenhongbinjs** [comment]
> 案例里不是有angular版本写法么

是有demo，但是没有具体的api文档。

**Comment by huxiaoyun** [comment]
demo 只提供模板渲染层怎么用。如果是 ng:if 这样的指令，按照ng 官方的文档来，组件就是一个普通的标签~
