### ISSUE TITLE
使用viser-ng的时候   const DataSet = require('@antv/data-set'); 报错

### ISSUE THREAD

**Issue by pxyi** [viserjs/viser#267]
const DataSet = require('@antv/data-set');

导致报错： Cannot find name 'require'.

请问应该如何解决

**Comment by huxiaoyun** [comment]
有木有install 这个包呢？？

这个包不在 viser-ng 的依赖里面哈~ 需要单独install

**Comment by W-Abel-jia** [comment]
请看这个文章：https://blog.csdn.net/wjyyhhxit/article/details/84893809
