### ISSUE TITLE
多条折线图是否可以通过alias属性修改tooltip文字

### ISSUE THREAD

**Issue by kuangyanit** [viserjs/viser#268]
如https://viserjs.github.io/demo.html#/viser/line/multi-line，如何修改tooltip上的"Tokyo"，"London"？ 单折线的时候可以通过给scale加上alias属性来修改tooltip文字，多折线是否可行（在暂不考虑以下两种方案的前提下）？

- 自定义tooltip
- 修改数据源结构或更改transform配置

**Comment by huxiaoyun** [comment]
可以通过给scale加上alias属性来修改tooltip文字，多折线是否可行

这种方法暂时不可行，因为 scale 作用的是源数据的字段，而多条线段是对某一个字段的拆分。

比如

```
const sourceData = [
  { month: 'Jan', Tokyo: 7.0, London: 3.9 },
  { month: 'Feb', Tokyo: 6.9, London: 4.2 },
];

```
如上数据，我们可以把 London 映射成 伦敦   Tokyo 映射成 东京，因为字段是本身存在的，而
https://viserjs.github.io/demo.html#/viser/line/multi-line  这个例子，是把数据处理变成

```
const sourceData = [
  { month: 'Jan', value: 7.0, city: 'Tokyo' },
 { month: 'Jan',  value: 3.9, city: 'London' },
  { month: 'Feb', value: 6.9, city: 'Tokyo' },
{ month: 'Feb', value: 4.2, city: 'London' },
];

```

现在已经没有 Tokyo  London 字段了，只能对 city 字段的值进行映射，也就是在 tooltip 进行映射。
