### ISSUE TITLE
viser-vue事件绑定方法

### ISSUE THREAD

**Issue by zhanghaofei** [viserjs/viser#271]
使用并非vue中常见的v-on方式进行事件监听，而是一个props。
参见viser源码
1. https://github.com/viserjs/viser/blob/master/packages/viser-vue/src/typed.ts
2. https://github.com/viserjs/viser/blob/master/packages/viser/src/utils/EventUtils.ts#L34

例如tooltip改变事件的监听如下

template:
```html
<v-tooltip :onChange="change"></v-tooltip>
```
script:
```js
methods: {
    change: function(ev){
        console.log(ev)
    }
}
```

**望尽快完善文档，仅仅说vue用法和react类似，但实际还是差别较大。看个要同时参照G2和Viser的教程、示例、API文档**

**Comment by huxiaoyun** [comment]
https://viserjs.github.io/demo.html#/viser/others/area-large   最好的方法就是看例子哦~

本周会写个专门的文档详细介绍下事件的使用。谢谢建议~

**Comment by huxiaoyun** [comment]
头像很可爱。萌萌的~ @zhanghaofei

**Comment by zhanghaofei** [comment]
基础用法看例子并不好找，例如这个事件的用法，只有极少数示例里面有，而且只有看了源码才知道有，非常难找。
同为喵星人🐱

**Comment by Bendjen** [comment]
老哥你绑定事件会出现重复监听的情况吗，我绑定了事件会跟随data的更新追加重复监听。
![tim 20181226183836](https://user-images.githubusercontent.com/20695625/50443433-66460d00-093e-11e9-82be-60acd8cad244.png)

**Comment by zhanghaofei** [comment]
不会哦，那应该是你写的有问题

**Comment by Bendjen** [comment]
> 不会哦，那应该是你写的有问题

只要触发了<v-chart>中的 data 的更新，中间所有组件用像:onClick这样的都会重复绑定监听。
data用静态值就不会，你看我写的应该没什么问题

**Comment by flym1013** [comment]
> 使用并非vue中常见的v-on方式进行事件监听，而是一个props。
> 参见viser源码
> 
> 1. https://github.com/viserjs/viser/blob/master/packages/viser-vue/src/typed.ts
> 2. https://github.com/viserjs/viser/blob/master/packages/viser/src/utils/EventUtils.ts#L34
> 
> 例如tooltip改变事件的监听如下
> 
> template:
> 
> ```
> <v-tooltip :onChange="change"></v-tooltip>
> ```
> 
> script:
> 
> ```js
> methods: {
>     change: function(ev){
>         console.log(ev)
>     }
> }
> ```
> 
> **望尽快完善文档，仅仅说vue用法和react类似，但实际还是差别较大。看个要同时参照G2和Viser的教程、示例、API文档**

v-guide 没有事件传入，能否把事件加入
