### ISSUE TITLE
viser-vue图表重绘及联动问题

### ISSUE THREAD

**Issue by zhanghaofei** [viserjs/viser#272]
viser-vue文档没有[DataSet图表联动](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/data-set.html#_%E5%9B%BE%E8%A1%A8%E8%81%94%E5%8A%A8%E7%A4%BA%E4%BE%8B)对应的示例，而参照DataSet文档示例做出的vue版能实现DataView根据状态量动态变化，但是图表并没有被重回（data已变化），怀疑是vue监听不到data变更所以未更新，但是想要this.$forceUpdate()手动重绘却没有合适的数据变更完毕的回调或者事件时机

**Comment by huxiaoyun** [comment]
https://viserjs.github.io/demo.html#/viser/components/special-data-and-range-mark  

这个例子就是通过改变data 重绘的呀~

**Comment by zhanghaofei** [comment]
需求比如：滑动图表1的日期，图表2自动变为展示图表1当前选择日期的数据
你说的这个例子就是直接给的数据绘制了，并不是像[DateSet状态量图表联动](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/data-set.html#_%E5%9B%BE%E8%A1%A8%E8%81%94%E5%8A%A8%E7%A4%BA%E4%BE%8B)一样。

后来调整后发现可以和上面G2示例一样的效果，但是有个问题，图表2自动变化后，图表1（已设置不监视状态量）也好像被重绘了，悬浮的tooltips会连续闪动多次然后消失，肯定是不正常的。


但是后来我通过vue的方式实现了G2示例相同效果，没有使用状态量，而是使用了vue的data中变量然后进行watch，监视到日期变化后对图表2重新sourcedata，代码相关片段如下：
![this.date模拟状态量](https://user-images.githubusercontent.com/14348610/49626861-ae949e00-fa16-11e8-9daa-fc0636b5b07d.png)
![选择图表1的日期后改变this.date](https://user-images.githubusercontent.com/14348610/49626919-ffa49200-fa16-11e8-91bc-0a9b9040a8e4.png)

![重新source数据](https://user-images.githubusercontent.com/14348610/49628751-0801ca80-fa21-11e8-9637-308f615b405f.png)


![transform使用this.date](https://user-images.githubusercontent.com/14348610/49626880-c9ffa900-fa16-11e8-8afb-09ce8a8102dc.png)


```

```
