### ISSUE TITLE
viser-vue中forceFit=true且初始化时时隐藏的会导致无法再显示

### ISSUE THREAD

**Issue by zhanghaofei** [viserjs/viser#275]
viser-vue中满足如下条件的情况：
1. forceFit=true时
2. 初始化（第一次source数据）时是隐藏的(例如在一个标签页中)

之后再使元素显示后无法显示图表，即使再次source()新的数据也不会显示。但是当改变视图大小（例如改变浏览器窗口大小后）即可立即显示

**暂时解决办法**
使视图可见后，通过触发窗口resize事件使其重新绘制
```js
window.dispatchEvent(new Event('resize'))
```

**Comment by huxiaoyun** [comment]
能给个demo 吗？ 
source()新的数据 ， 这里是没有重绘的，vue 的重绘是和数据绑定的，你试着把数据作为状态传给 chart 标签哦。

数据变化后，自动会触发 vue 的重绘机制。

**Comment by zhanghaofei** [comment]
就是一个图表正常的配置，但是display:none，然后source()加载数据后，再把display:none去掉，发现图表不会显示，必须改变下浏览器窗口大小才会显示

**Comment by huxiaoyun** [comment]
这个dispaly: none 是在外层div?? 

能在这里写个例子么 https://jsfiddle.net/   谢谢~

**Comment by PLQin** [comment]
nice, Solved my problem
