### ISSUE TITLE
百分比Y轴问题

### ISSUE THREAD

**Issue by yang217** [viserjs/viser#276]
我的数据是浮点单位，定义格式是{
          dataKey:"跳出率",
          min: 0,
          formatter: ".0%",
          max:1
         },
但是绘出来不是我想要的，是哪里需要配置吗，还是数据格式不对
![qq 20181123112949](https://user-images.githubusercontent.com/23252691/48927757-cb5bac80-ef13-11e8-869b-4f7baae8f579.jpg)

**Comment by plqin-xiaohao** [comment]
@yang217 老铁 , 你是否找到了解决方案, 求分享
