### ISSUE TITLE
环形图toottip如何显示自定义内容 我想多显示百分比处理前的数据

### ISSUE THREAD

**Issue by yang217** [viserjs/viser#277]
![image](https://user-images.githubusercontent.com/23252691/49007948-a717fe00-f1a7-11e8-81e1-cc25375cf39d.png)
![image](https://user-images.githubusercontent.com/23252691/49007976-b8f9a100-f1a7-11e8-8725-349305446111.png)

**Comment by huxiaoyun** [comment]
自定义tooltip 哦~
