### ISSUE TITLE
Percentage Accuracy of Basic Ring Diagram

### ISSUE THREAD

**Issue by bosens-China** [viserjs/viser#278]
problem

I don't want components to give up for me. Suppose there's a set of data.

DistData = [

{item: level 1 heat, count: 99.99},

{item: Level 2 heat, count: 0.01},

{item: Level 3 heat, count: 0},

{item: level 4 heat, count: 0},

{item: level 5 heat, count: 0}

];

display：
![1](https://user-images.githubusercontent.com/39508895/49263703-a07ad680-f486-11e8-9716-36876656e7a0.png)
![2](https://user-images.githubusercontent.com/39508895/49263705-a1136d00-f486-11e8-96ac-f2e4b3362628.png)

Code：
DistData = [

{item: level 1 heat, count: 99.99},

{item: Level 2 heat, count: 0.01},

{item: Level 3 heat, count: 0},

{item: level 4 heat, count: 0},

{item: level 5 heat, count: 0}

];
const dvDist = new DataSet.View().source(distData);
          dvDist.transform({
            type: "percent",
            field: "count",
            dimension: "item",
            as: "percent",
              
          });
`

**Comment by huxiaoyun** [comment]
sorry  ， i cannot get ur problem.

u can  describe ur problems， like  ur  explaination  chart  and   current  viser  render result,   the differentce between them
