### ISSUE TITLE
showTitle is not working for axis

### ISSUE THREAD

**Issue by vcrh88** [viserjs/viser#279]
![image](https://user-images.githubusercontent.com/4470664/49284786-9978b600-f4d0-11e8-91b0-2bf18e4ae0cd.png)

                <v-chart :force-fit="true" :height="height" :data="data" :scale="scale" :padding="[20, 20, 60, 20]">
                    <v-tooltip />
                    <v-axis :data-key="'count'" showTitle="'false'" />
                    <v-smooth-line position="hour*count" />
                    <v-bar position="hour*count" :label="lineLabelConfig" />
                </v-chart>

a ugly solution:
const yLabelConfig = {
    formatter: (val, item) => {
        return ''
    }
}

**Comment by huxiaoyun** [comment]
use wrong api,   try like this:

![image](https://user-images.githubusercontent.com/4345248/49624970-9587ef00-fa0e-11e8-88fe-99e8275b1fc1.png)


```
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip />
      <v-axis data-key="year" :label="false"/>
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>
  </div>
</template>

<script>
const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  min: 0,
  max: 1,
}];

export default {
  data() {
    return {
      data,
      scale,
      height: 400,
    };
  }
};
</script>
```
