### ISSUE TITLE
viser-vue 在 nuxt ssr上面不能正常显示

### ISSUE THREAD

**Issue by ShiveringPan** [viserjs/viser#282]
[测试地址](https://llvzl4yjmz.sse.codesandbox.io/chart)

![image](https://user-images.githubusercontent.com/25818289/49571676-eb0fbd80-f974-11e8-9e7b-10ca5c872e90.png)

**Comment by huxiaoyun** [comment]
@kingoo

**Comment by kinghoo5201** [comment]
@ShiveringPan能提供代码吗，没代码看不出效果来

**Comment by kinghoo5201** [comment]
而且图表类不推荐ssr，你ssr产生的代码
![image](https://user-images.githubusercontent.com/25658415/51971983-71e4a080-24b5-11e9-81e7-6d9f3ac15344.png)
都是未渲染完成的代码（自定义标签未经viser解析成正常dom），viser是要将数据渲染成canvas或者svg的，而你这里只是ssr出了一些库里的自定义标签，而完全没有渲染出具体的dom

viser官网中的例子可以看出
![image](https://user-images.githubusercontent.com/25658415/51972130-b5d7a580-24b5-11e9-926e-df70ff586e75.png)
viser渲染的目标如果是canvas，你需要有有js部分来渲染canvas，单单渲染出canvas是不会有图形的，
所以图表类不推荐ssr

@ShiveringPan
