### ISSUE TITLE
v-slider的handleStyle属性不生效

### ISSUE THREAD

**Issue by Eamonnzhang** [viserjs/viser#285]
[https://viserjs.github.io/demo.html#/viser/stock/stock](https://viserjs.github.io/demo.html#/viser/stock/stock)

官方示例更改：
![image](https://user-images.githubusercontent.com/9126544/49633059-ead5f780-fa32-11e8-9556-5abea5285300.png)
handleStyle的值如下：
`handleStyle: {
        img: 'http://chuiyi-crm.champzee.com/image/chart/chart-slider.png', 
       width: 20,
        height: 46
      },`
结果还是默认的：
![image](https://user-images.githubusercontent.com/9126544/49633103-1953d280-fa33-11e8-9984-fb783a483ee6.png)

**Comment by MiaoJianxue** [comment]
这个问题咋解决的？viser设置slider的handelStyle属性也没有生效？不知道是什么原因
