### ISSUE TITLE
Slider需要更新

### ISSUE THREAD

**Issue by sgguo** [viserjs/viser#288]
发现了slider的两个问题，1. start 和 end 不会随着设置的值进行更新，这个slider 本身已经更新https://github.com/antvis/g2-plugin-slider，在v2.1.1中。2. 当data更新时，slider里的该蓝图没有更新。这个不知道是slider本身的bug，还是viser的问题。

**Comment by huxiaoyun** [comment]
https://github.com/viserjs/viser/pull/286   代码已 merge  ， 待发布

**Comment by sgguo** [comment]
好的。

**Comment by sjs9860** [comment]
I have tried adding componentWillReceiveProps which do the same thing as componentDidMount. Slider could up to date according to its config change (like start and end)

**Comment by kinghoo5201** [comment]
https://viserjs.github.io/demo.html#/viser/others/area-large

**Comment by kinghoo5201** [comment]
https://viserjs.github.io/demo.html#/viser/others/area-large

**Comment by huxiaoyun** [comment]
https://github.com/viserjs/viser/pull/331/files    bugfix
