### ISSUE TITLE
viser-ng如何导入主题配置数据

### ISSUE THREAD

**Issue by raintreebe** [viserjs/viser#289]
在主题工具中导出的配置数据如何在使用viser-ng时导入

**Comment by Enginebeck** [comment]
同问，如何在react中导入主题配置

**Comment by Enginebeck** [comment]
> 同问，如何在react中导入主题配置

@raintreebe 找到了，看[g2](https://www.yuque.com/antv/g2-docs/api-chart)的文档
![image](https://user-images.githubusercontent.com/9574537/50065610-63d30d00-01f2-11e9-8559-64960fefb309.png)
