### ISSUE TITLE
viser-ng的图表动画效果怎么都是一闪而过？

### ISSUE THREAD

**Issue by canwen** [viserjs/viser#293]
>对比了官网示例里面的React、Vue和Angular版本，发现React和Vue版本的动画效果都和G2官网的一样，就只有Angular版本的动画效果是一闪而过，感觉是动画的执行时间被设置了一个很短的时间就完成了一样，但是通过对v-line等组件设置animate属性的动作时间却没有任何的效果，这是不是有bug？

**Comment by huxiaoyun** [comment]
help wanted ...

maybe this line cause too short animate   https://github.com/viserjs/viser/blob/master/packages/viser-ng/src/Chart.ts#L428  

need some optimize , can u pull a merge request ?
