### ISSUE TITLE
Register theme with viser-ng?

### ISSUE THREAD

**Issue by BaymaxGroot** [viserjs/viser#302]
Hi all,

   I have download a them json file from https://viserjs.github.io/theme.html,
   then just want to know how to register theme with viser-ng in Angular 2+ framework!

   very urgent!

Thanks

**Comment by huxiaoyun** [comment]
https://github.com/viserjs/viser/issues/256

**Comment by huxiaoyun** [comment]
```
// theme color
var theme = {
  // data
}
// register theme
import { Global } from 'viser-vue';
Global.registerTheme('myTheme', theme)
//注册完后，设置主题
Global.setTheme('myTheme')

```
