### ISSUE TITLE
如何使用G2 Chart Instance的filter和repaint进行自定义的legend？

### ISSUE THREAD

**Issue by francisfeng** [viserjs/viser#318]
这里是示例：https://codesandbox.io/s/yw57xxwo71

我想根据Ant Design Pro的雷达图样式，模仿一个Vue版本的。点击「个人」、「团队」或「部门」后，对应的线条应该消失。具体的实际效果如[工作台 - Ant Design Pro](https://preview.pro.ant.design/dashboard/workplace)。

antp的实现在这里：https://github.com/ant-design/ant-design-pro/blob/master/src/components/Charts/Radar/index.js#L68

但是依样画葫芦后，`this.chart.repaint`始终没有效果，具体请见codesandbox内的`handleLegendClick`函数。

查遍文档后，仍然找不到结果。

请问应当如何使得filter过后的repaint生效？

**Comment by huxiaoyun** [comment]
filter demo:  暂时没放官网

https://github.com/viserjs/viser/blob/master/demo/chart/bar-1

**Comment by francisfeng** [comment]
Problem solved. 

我已更新示例，供遇到相同问题的朋友参考。

keyword: filter, v-view
