### ISSUE TITLE
change dataRegion start to end color

### ISSUE THREAD

**Issue by calebeaires** [viserjs/viser#319]
Region guide has a style fill property that changes area color, but dataRegion does not. How to change that color?

<img width="943" alt="screen shot 2019-01-23 at 10 15 28" src="https://user-images.githubusercontent.com/794195/51606137-387dc500-1ef8-11e9-954b-08b3497339e8.png">

**Comment by huxiaoyun** [comment]
@kinghoo5201

**Comment by kinghoo5201** [comment]
whitch package you used@calebeaires

**Comment by calebeaires** [comment]
@kinghoo5201 Vue

**Comment by kinghoo5201** [comment]
We find a G2 bug that when guide's type is dataRegion,it could not set dataRegion's fill color
my codepen's url:https://codepen.io/kinghoo5201/pen/pGNNro?editors=1000
when i use region :
![image](https://user-images.githubusercontent.com/25658415/51970225-4f508880-24b1-11e9-9555-9d70323134d7.png)
when i use dataRegion:
![image](https://user-images.githubusercontent.com/25658415/51970245-5e373b00-24b1-11e9-9176-614c59e7c27e.png)

g2 issue's url:https://github.com/antvis/g2/issues/1172
@calebeaires
