### ISSUE TITLE
viser-ng 的 Box标签 style属性 的  fillOpacity  属性不支持

### ISSUE THREAD

**Issue by huxiaoyun** [viserjs/viser#32]
<Chart [forceFit]="forceFit" [height]="height" >
      <View viewId="1" [data]="data" [dataPre]="dataPre" [scale]="scale">
        <Tooltip [showTitle]="tooltipOpts.showTitle" [crosshairs]="tooltipOpts.crosshairs" [itemTpl]="tooltipOpts.itemTpl"></Tooltip>
        <Axis></Axis>
        <Box position="x*range" [style]="boxStyle" [tooltip]="boxTooltip"></Box>
      </View>
      <View viewId="4" [data]="data" [scale]="scale">
        <Point [position]="'x*range'" [size]="3" [active]="false"></Point>
      </View>
    </Chart>

const boxStyle = {
  stroke: '#545454',
  fill: '#1890FF',
  fillOpacity: 0.3
};

**Comment by linhuiw** [comment]
有Demo 可以重现这个问题么?
