### ISSUE TITLE
viser-graph-react 有些事件不生效

### ISSUE THREAD

**Issue by leavest** [viserjs/viser#322]
文档中所有的事件  
  onClick?: func; 鼠标单击
  onAfterchange?: func; 数据改变后
  onMousedown?: func; 鼠标按下
  onMousemove?: func; 鼠标移动
  onMouseleave?: func; 鼠标离开画布区域
  onMouseup?: func; 鼠标抬起
  onDblclick?: func; 鼠标双击
  onTouchstart?: func; 手指触摸
  onTouchmove?: func; 手指移动
  onTouchend?: func; 手指离开
  onPlotenter?: func; 进入图表时
  onPlotmove?: func; 在图表上移动时
  onPlotleave?: func; 从图表离开时
  onPlotclick?: func; 单击图表时
  onPlotdblclick?: func; 双击图表时
  onDragstart?: func; 开始拖动时
  onDrag?: func; 拖动中
  onDragend?: func; 拖动结束时

只有 onClick onAfterchange  onDragstart  onDrag  onDragend有效，其他事件都触发不了。
这是我写的demo
https://github.com/leavest/viser-draph-demo
哪里写错了。

**Comment by huxiaoyun** [comment]
@kinghoo5201

**Comment by kinghoo5201** [comment]
> 文档中所有的事件
> onClick?: func; 鼠标单击
> onAfterchange?: func; 数据改变后
> onMousedown?: func; 鼠标按下
> onMousemove?: func; 鼠标移动
> onMouseleave?: func; 鼠标离开画布区域
> onMouseup?: func; 鼠标抬起
> onDblclick?: func; 鼠标双击
> onTouchstart?: func; 手指触摸
> onTouchmove?: func; 手指移动
> onTouchend?: func; 手指离开
> onPlotenter?: func; 进入图表时
> onPlotmove?: func; 在图表上移动时
> onPlotleave?: func; 从图表离开时
> onPlotclick?: func; 单击图表时
> onPlotdblclick?: func; 双击图表时
> onDragstart?: func; 开始拖动时
> onDrag?: func; 拖动中
> onDragend?: func; 拖动结束时
> 
> 只有 onClick onAfterchange onDragstart onDrag onDragend有效，其他事件都触发不了。
> 这是我写的demo
> https://github.com/leavest/viser-draph-demo
> 哪里写错了。

看了下你的demo，写法都没有错误，viser-graph-react底层基于antv-g6实现的，
https://github.com/viserjs/viser/blob/master/packages/viser-graph/src/graph.ts#L97 源码中的事件名未按照https://www.yuque.com/antv/g6/api-graph g6文件中的事件名来实现导致的，@huxiaoyun
===============================
解决方案：按照g6文档中的事件名https://www.yuque.com/antv/g6/api-graph 'on'+'EventName'的形式来书写事件来实现事件吧

**Comment by kinghoo5201** [comment]
这是我的g6 demo：https://codepen.io/kinghoo5201/pen/mvEbjN

**Comment by leavest** [comment]
> 这是我的g6 demo：https://codepen.io/kinghoo5201/pen/mvEbjN

这是要自己封装一个组件吗可以给个viser的demo吗？

**Comment by kinghoo5201** [comment]
> > 这是我的g6 demo：https://codepen.io/kinghoo5201/pen/mvEbjN
> 
> 这是要自己用g6封装一个react组件吗？
> 可以给个viser实现的demo吗？

我拿你的组件举个例子

**Comment by kinghoo5201** [comment]
`onAfterchange: () => {
    console.log("onAfterchange");
  },
  onMousedown: () => {
    console.log("onMousedown");
  },
  onMousemove: () => {
    console.log("onMousemove");
  },
  onMouseleave: () => {
    console.log("onMouseleave");
  },
  onMouseup: () => {
    console.log("onMouseup");
  },
  onDblclick: () => {
    console.log("onDblclick");
  },
  onTouchstart: () => {
    console.log("onTouchstart");
  },
  onTouchmove: () => {
    console.log("onTouchmove");
  },
  onTouchend: () => {
    console.log("onTouchend");
  },
  onPlotenter: () => {
    console.log("onPlotenter");
  },
  onPlotmove: () => {
    console.log("onPlotmove");
  },
  onPlotleave: () => {
    console.log("onPlotleave");
  },
  onPlotclick: () => {
    console.log("onPlotclick");
  },
  onPlotdblclick: () => {
    console.log("onPlotdblclick");
  },
  onDragstart: () => {
    console.log("onDragstart");
  },
  onDrag: () => {
    console.log("onDrag");
  },
  onDragend: () => {
    console.log("onDragend");
  },`
这些是你写的事件

实际上onClick onAfterchange onDragstart onDrag onDragend事件生效是因为这些事件在g6中存在

g6的全部事件如下：
`
graph.on('click', (ev)=>{});             // 鼠标左键点击事件
graph.on('dblclick', (ev)=>{});          // 鼠标左键双击事件
graph.on('mouseenter', (ev)=>{});        // 鼠标移入事件
graph.on('mouseleave', (ev)=>{});        // 鼠标移出事件
graph.on('mousedown', (ev)=>{});         // 鼠标按下事件
graph.on('mouseup', (ev)=>{});           // 鼠标抬起事件
graph.on('mousemove', (ev)=>{});         // 鼠标移动事件
graph.on('dragstart', (ev)=>{});         // 鼠标开始拖拽事件
graph.on('drag', (ev)=>{});              // 鼠标拖拽事件
graph.on('dragend', (ev)=>{});           // 鼠标拖拽结束事件
graph.on('dragenter', (ev)=>{});         // 鼠标拖拽进入事件
graph.on('dragleave', (ev)=>{});         // 鼠标拖拽移出事件
graph.on('drop', (ev)=>{});              // 鼠标拖拽放置事件
graph.on('contextmenu', (ev)=>{});    //菜单事件
graph.on('keydown', function(ev){});             // 键盘按键按下事件
graph.on('keyup', function(ev){});               // 键盘按键抬起事件
graph.on('wheel', function(ev){});               // 滚轮事件
graph.on('beforechangesize', function(ev){})     // 画布尺寸变化前
graph.on('afterchangesize', function(ev){})      // 画布尺寸变化后
graph.on('beforeviewportchange', function(ev){}) // 视口变化前
graph.on('afterviewportchange', function(ev){})  // 视口变化后
graph.on('beforechange', function(ev){})         // 子项数据变化前
graph.on('afterchange', function(ev){})          // 子项数据变化后  
`
想要用g6的事件只要用  比如mouseup事件在viser-react-graph中药写成onMouseup
mousedown要写成 onMouseDown
而由于文档的失误，onTouchstart等等这些事件是不存在的。。。
这样就行啦@leavest

**Comment by kinghoo5201** [comment]
补充下：viser-graph中是这样调用g6事件的：
Object.keys(this.config.events || []).forEach((k) => {
      const eventName = k.replace('on', '').toLocaleLowerCase();
      this.graph.on(eventName, (ev: any) => {
        this.config.events[k](ev, this.graph);
      });
    });

**Comment by leavest** [comment]
@kinghoo5201 👌谢谢

**Comment by leavest** [comment]
有时间的话希望更新一个文档吧

**Comment by huxiaoyun** [comment]
@kinghoo5201   麻烦更新下文档

**Comment by magickaichen** [comment]
看了这个更新过后的文档：https://www.yuque.com/rs385i/atlsqh/rqvnby
然而onDbclick这个事件还是没生效，我的写法是：
```js
<Chart forceFit height={400} padding={[20, 80, 50, 110]} data={data} ondblclick={()=>alert('你点我啦！')}>
  <Coord type="rect" direction="LB" />
  <Tooltip />
  <Legend />
  <Axis dataKey="profession" label={{ offset: 12 }} />
  <Bar position="profession*range" />
</Chart>
```
