### ISSUE TITLE
viser-ng 如何在堆叠条形图添加内部文本

### ISSUE THREAD

**Issue by wj0075** [viserjs/viser#332]
类似于G2的案例demo展示所示
![image](https://user-images.githubusercontent.com/23044894/52757936-65c61a80-3041-11e9-8ceb-9a4314515c35.png)

**Comment by huxiaoyun** [comment]
@kinghoo

**Comment by kinghoo5201** [comment]
稍等，coding...@wj0075

**Comment by kinghoo5201** [comment]
it's demo:https://codepen.io/kinghoo5201/pen/mvGOaE
@wj0075

**Comment by wj0075** [comment]
@kinghoo5201 辛苦哈，谢谢

**Comment by huxiaoyun** [comment]
mark ， 添加到官网
