### ISSUE TITLE
请问在demo中的数据源如何下载？

### ISSUE THREAD

**Issue by Doug44444444** [viserjs/viser#336]
比如Bubble Map中的worldGeo.json和map-1.json。感谢！

**Comment by kinghoo5201** [comment]
打开浏览器开发者调试工具，切换到network，选择xhr
![image](https://user-images.githubusercontent.com/25658415/53225423-f2608080-36b2-11e9-9178-e054758a3029.png)
当你需要的那条数据载入后右键选择open in new tab(新标签打开)，然后command+s进行保存就行了
@Doug44444444,上面的操作可以在你需要数据的那个demo页面中用开发者工具找到，或者它请求的地址都是相对的'/assets/xxx/xxx.json',可以直接用域名来拼接它viserjs.github.io/assets/xxx/xxx.json
