### ISSUE TITLE
[Bug Report] viser-vue 的 slider 插件在拖动的时候不停新增

### ISSUE THREAD

**Issue by francisfeng** [viserjs/viser#337]
![slider-plugin-repaint-bug](https://i.loli.net/2019/02/22/5c6f9895b1aab.png)

如图，[示例](https://codesandbox.io/s/jjz1q5qn99)在这里，基本上就是官网的[雨量流量对比](https://viserjs.github.io/demo.html#/viser/others/rainfall-traffic-contrast)，仅仅改动了 jQuery 引入数据部分。

版本是目前最新的`viser-vue": "^2.4.5"`.

**Comment by hwen-mustard** [comment]
+1 不过在官方示例的 vue demo 里，没这个问题，代码拷到本地就有了，神奇

**Comment by huxiaoyun** [comment]
bug 已经fix ，官网忘记更新了。

demo：
https://github.com/viserjs/viser/blob/master/demo/chart/slider/vue.vue

**Comment by PHenryy** [comment]
+1 我是根据官网的 股票图 写的，调试了3个小时 ... 刚看到这个bug
