### ISSUE TITLE
viser-vue，v-chart 重新设置 data 属性后，出现点击事件重复触发的问题

### ISSUE THREAD

**Issue by hwen-mustard** [viserjs/viser#338]
复现步骤：
1. 初始定义简写
```html
<button @click="reset">RESET</button>
<v-chart :data="data">
    <v-stack-bar :onClick="test"></v-stack-bar>
</v-chart>
```
```javascript
let data = Data

let test () {console.log('clicked')}
let reset () {data = RandomNewData}
```

2. 点击 bar，log: 
```
clicked
```

3. 点击 `RESET` 按钮两次, 画面改变两次 => 点击 bar, log:
```
clicked
clicked
clicked
```

打印出来的行数不一定会是三个，但是一定不是一个...

**Comment by hwen-mustard** [comment]
[示例地址](https://codesandbox.io/s/k5o5p415pv)

**Comment by huxiaoyun** [comment]
emmm. 估计是事件重新绑定了。

**Comment by hwen-mustard** [comment]
[#300 issue](https://github.com/viserjs/viser/issues/300) 已解决

**Comment by hwen-mustard** [comment]
[示例地址](https://codesandbox.io/s/k5o5p415pv) 已换上 fix 的方法

**Comment by Polaris-z** [comment]
当前点击的图例本来是需要改变颜色的   加上key之后 重新渲染后颜色重置了
![image](https://user-images.githubusercontent.com/28984303/65315247-522bf500-dbca-11e9-91f3-986f0653d6f4.png)
![Uploading image.png…]()
