### ISSUE TITLE
请提示一下Angular下如何注册Theme

### ISSUE THREAD

**Issue by min-ye** [viserjs/viser#339]
npm install @antv/g2
之后
import G2 from '@antv/g2';报错;
Module '"/.../node_modules/@antv/g2/lib/index"' has no default export.
请问我如何才能import G2并注册theme。谢谢。

**Comment by huxiaoyun** [comment]
啊？ 为什么import g2 

参考官网主题实现： https://github.com/viserjs/viserjs.github.io/blob/master/pages/theme/layout/Right/index.tsx

这里可以配色下载： https://viserjs.github.io/theme.html
