### ISSUE TITLE
图表数据如何更新

### ISSUE THREAD

**Issue by bosens-China** [viserjs/viser#340]
如题，我使用了@antv/data-set创建初始数据，但是我参照g2更新方法提示.changeData is not a function，
还有饼状图的分割线大小可以通过Viser.registerShape来定义，那么在viser中是什么方法呢？

**Comment by huxiaoyun** [comment]
changeData 利用 框架的 自动更新机制呀 , 有很多demo 啊

https://viserjs.github.io/demo.html#/viser/components/special-data-and-range-mark

这个例子就是获取后端数据，通过更新 state 重绘图表

**Comment by bosens-China** [comment]
> changeData利用框架的自动更新机制呀，有很多演示啊
> 
> https://viserjs.github.io/demo.html#/viser/components/special-data-and-range-mark
> 
> 这个例子就是获取后端数据，通过更新状态重绘图表
可否给出一个具体一些的，我现在想要实现的是，初始化图标之后，如果接收到新的数据会重绘数据
上面你给的例子
我尝试了一下
``` js
  mounted() {
    $.getJSON('/assets/data/income.json', (sourceData) => {
      this.$data.data = sourceData;
      setTimeout(() => {
          this.data = this.data.slice(0, 100)
      }, 5000);
    });
  },
```
所以正确的做法是什么
