### ISSUE TITLE
关于图表动态问题

### ISSUE THREAD

**Issue by xingyys** [viserjs/viser#35]
viser-vue怎么做动态的图表呢？

**Comment by huxiaoyun** [comment]
有交互的？？？还是数据刷新？数据刷新的话重新渲染一遍。

**Comment by arcthur** [comment]
vue 怎么做就怎么做

**Comment by fenceer** [comment]
动态更新数据有重影  大家遇到过吗？

**Comment by snokier** [comment]
@fenceer +1

**Comment by PLQin** [comment]
viser版本 : 2.4.1 ; 
动态的数据无法在视图上呈现

**Comment by PLQin** [comment]
我已经解决了这个问题 , 使用 : 
```
      window.dispatchEvent(new Event('resize')); 
```

初使用者很大概率会遇到这个问题, 建议在api文档中建立索引

**Comment by PLQin** [comment]
> @PLQin @snokier please leave a demo

我的问题和 #275 一样
