### ISSUE TITLE
双轴图表生成图例不完整

### ISSUE THREAD

**Issue by ShawshankLin** [viserjs/viser#350]
这样创建的图表，左边有两条折线，右边一条折线，但是图例只显示左边的两个
```<v-chart  :force-fit="true" :height="height" :data="getTransformData" :padding="padding" :scale="scale">
              <v-tooltip :crosshairs="{ type: 'line' }" />
              <v-axis dataKey="value" />
              <v-legend />
              <view data={getTransformData}>
                <v-line position="date*value" :size="2" color="key" />
                <v-area position="date*value" color="key" opacity="0.05"/>
              </view>
              <view data={getTransformData2}>
                <v-smooth-line position="date*roleCreateNum" color="#fdae6b" :size="gemoSize" />
                <v-point shape="circle" position="date*roleCreateNum" color="#fdae6b" :size="gemoSize" />
                <!-- <v-line position="date*roleCreateNum" />
                <v-point position="date*roleCreateNum" shape="circle" /> -->
                <!-- <v-line position="date*value" :size="2" color="key" />
                <v-area position="date*value" color="key" opacity="0.05"/> -->
              </view>
            </v-chart>```

**Comment by ShawshankLin** [comment]
@huxiaoyun

**Comment by huxiaoyun** [comment]
view层是这样的，如果只有一个数据系列 legend 会隐藏

**Comment by ShawshankLin** [comment]
> view层是这样的，如果只有一个数据系列 legend 会隐藏

那应该怎么修改呢？再加一个 <v-legend />？

**Comment by huxiaoyun** [comment]
放到一个view层，然后增加  axis
```
<v-axis dataKey="value" position="left" />
<v-axis dataKey="roleCreateNum"  position="right"/>
```

**Comment by ShawshankLin** [comment]
> 放到一个view层，然后增加 axis

<v-chart  :force-fit="true" :height="height" :data="getData" :padding="padding" :scale="scale">
              <v-tooltip :crosshairs="{ type: 'line' }" />
              <view>
                <v-axis dataKey="value" position="left" />
                <v-axis dataKey="roleCreateNum"  position="right"/>
                <v-legend dataKey="value"/>
                <v-line position="date*value" :size="2" color="key" />
                <v-area position="date*value" color="key" opacity="0.05"/>
                <v-line position="date*roleCreateNum" color="#fdae6b"  />
                <v-area  position="date*roleCreateNum" color="#fdae6b" opacity="0.05"  />
              </view>
            </v-chart>

是这样吗？
