### ISSUE TITLE
如何设置横轴显示范围

### ISSUE THREAD

**Issue by HOTTIN** [viserjs/viser#351]
![image](https://user-images.githubusercontent.com/12428754/54808890-8460a680-4cbc-11e9-959c-da19e3b7f481.png)
如图
想要通过滑块设置显示范围的缩放，范围外的行，比如task2就显示空白的一行，
请问如何只设置X轴比例尺的起止区间？

**Comment by huxiaoyun** [comment]
https://viserjs.gitee.io/demo.html#/viser/stock/stock   这个案例能解决问题吗？

**Comment by HOTTIN** [comment]
这个案例是通过filter把数据过滤掉了，我这个区间图，只是想控制横轴的显示范围，但是y轴数据列不希望被过滤减少

**Comment by huxiaoyun** [comment]
https://github.com/viserjs/viser/blob/master/demo/chart/bar-1/react.tsx 

试试这个案例呢？ filter 数据。

![image](https://user-images.githubusercontent.com/4345248/55302123-4ad52b80-5472-11e9-8c20-2a35b716a0dd.png)
