### ISSUE TITLE
关于基础条形图的几点疑问

### ISSUE THREAD

**Issue by kuangyanit** [viserjs/viser#353]
1. 官网基础条形图实例预期的排序方式是什么？ 正序？

2. 目前发现在windows下不同版本（旧版本跟最新版本）的chrome中该实例会有正、倒序两种不同的呈现，升级至最新版本之后均呈现正序，是支持问题么？

**Comment by huxiaoyun** [comment]
啊。瞅一瞅。
chrome中该实例会有正、倒序两种不同的呈现 这个是哪个版本？

最新版本这个是哪个版本？

**Comment by kuangyanit** [comment]
此处提及的旧版本是67.0.3396.87，最新版本是73.0.3683.86

**Comment by huxiaoyun** [comment]
你这是chrome 版本啊。viser 版本有差异吗？
