### ISSUE TITLE
failed to run demo, Cannot find module './ErrorBar'.

### ISSUE THREAD

**Issue by uptonking** [viserjs/viser#36]
I tried to run viser demo following your guide.
```
$ npm run postinstall
$ cd ./demo && npm install
$ npm run start
```

when exec the last command, here is the error msg
```
ERROR in ../packages/viser/src/shapes/loadShapes.ts
(2,27): error TS2307: Cannot find module './ErrorBar'.

ERROR in ../packages/viser/src/shapes/loadShapes.ts
Module not found: Error: Can't resolve './ErrorBar' in '/root/Downloads/viser/packages/viser/src/shapes'
 @ ../packages/viser/src/shapes/loadShapes.ts 4:15-36
 @ ../packages/viser/src/core/CommonChart.ts
 @ ../packages/viser/src/index.ts
 @ ./chart/bar-1/json.ts
 @ ./chart ^\.\/.*$
 @ ./index.ts
 @ multi ./index.ts
webpack: Failed to compile.
```

then I checked the file  `/path/to/packages/viser/src/shapes/loadShapes.ts`  and the file `/path/to/packages/viser/src/shapes/Errorbar.ts`
I cannot find any error, in grammar.

any help?

my develop env is node 8.9.1, npm 5.5.1

**Comment by ascoders** [comment]
@arcthur The file name `ErrorBar` should be `Errorbar` in `loadShapes.ts`

**Comment by uptonking** [comment]
我也是眼瞎了，还检查了几遍文件的语法 :confounded:
