### ISSUE TITLE
多数据源的折线图，可以按照数据源设置不同的折线形状吗？比如在同一个坐标系中有的设置实线有的设置虚线

### ISSUE THREAD

**Issue by CarlKong** [viserjs/viser#360]
多数据源的折线图，可以按照数据源设置不同的折线形状吗？比如在同一个坐标系中有的设置实线有的设置虚线

**Comment by huxiaoyun** [comment]
可以啊。设置类型  https://www.yuque.com/rs385i/yzbt72/zrumt7
