### ISSUE TITLE
数据里面的第一个点在X轴上  ，留白的这个操作，使用的什么属性啊。 有大佬用过吗？

### ISSUE THREAD

**Issue by GitHub-zhangshun** [viserjs/viser#361]

**Comment by huxiaoyun** [comment]
什么需求？？ 不太懂。。。。留白 = =

**Comment by huxiaoyun** [comment]
nice: false  么？

**Comment by GitHub-zhangshun** [comment]
boundaryGap :false   是这个在xAxis里面进行设置




------------------ 原始邮件 ------------------
发件人: "Ludy Hu"<notifications@github.com>; 
发送时间: 2019年4月24日(星期三) 下午3:01
收件人: "viserjs/viser"<viser@noreply.github.com>; 
抄送: "忍の時代は 終わる"<1260403690@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [viserjs/viser] 数据里面的第一个点在X轴上  ，留白的这个操作，使用的什么属性啊。 有大佬用过吗？ (#361)




nice: false  么？

**Comment by GitHub-zhangshun** [comment]
那个东西，我是在echarts里面找到的，但我不知道在viser里面是哪个属性



------------------ 原始邮件 ------------------
发件人: "Ludy Hu"<notifications@github.com>; 
发送时间: 2019年4月18日(星期四) 晚上9:49
收件人: "viserjs/viser"<viser@noreply.github.com>; 
抄送: "TNT"<1260403690@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [viserjs/viser] 数据里面的第一个点在X轴上  ，留白的这个操作，使用的什么属性啊。 有大佬用过吗？ (#361)




什么需求？？ 不太懂。。。。留白 = =

**Comment by huxiaoyun** [comment]
你能用图表举个例子么，  boundaryGap :false  会影响图表什么

**Comment by GitHub-zhangshun** [comment]
就是这种效果，因为我们UI给我的效果图就是这样的，第一个点需要从Y轴上开始
但我在viser里面没有找到这个属性，可以让数据在Y轴开始。
boundaryGap :false这个属性在echarts里面可以将数据的第一个点和最后一个点的位置固定在这个图标的两边。
不知道viser里面有没有这个属性
------------------ 原始邮件 ------------------
发件人: "Ludy Hu"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 晚上11:19
收件人: "viserjs/viser"<viser@noreply.github.com>;
抄送: "TNT"<1260403690@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [viserjs/viser] 数据里面的第一个点在X轴上  ，留白的这个操作，使用的什么属性啊。 有大佬用过吗？ (#361)




你能用图表举个例子么，  boundaryGap :false  会影响图表什么

**Comment by huxiaoyun** [comment]
试试这个例子, 保证显示 first last  x axis label

![image](https://user-images.githubusercontent.com/4345248/56844491-7ae1e400-68e3-11e9-99dd-8a496d506171.png)


```
import { Chart, Tooltip, Axis, Line, Area, Guide } from 'viser-react';
import * as React from 'react';
const DataSet = require('@antv/data-set');
import * as $ from 'jquery';

const scale = [
  {
    dataKey: 'time',
    range: [0, 1],
    nice: true,  // !!!!! 看这里
  },
];

const guides = [
  {
    type: 'dataMarker',
    position: ['2014-01-03', 6.763],
    content: '受稳健货币政策影响，协定存款利\n率居高不下,收益率达6.763%',
    style: {
      text: {
        textAlign: 'left',
      },
    },
  },
  {
    type: 'dataMarker',
    position: ['2013-05-31', 2.093],
    content: '余额宝刚成立时，并未达到目标资产\n配置，故收益率较低',
    style: {
      text: {
        textAlign: 'left',
      },
    },
  },
  {
    type: 'dataMarker',
    position: ['2016-09-04', 2.321],
    content: '受积极货币政策的影响，收益率降\n到历史最低2.321%',
    style: {
      text: {
        textAlign: 'left',
      },
    },
  },
  {
    type: 'dataRegion',
    start: ['2016-12-02', 2.517],
    end: ['2017-03-24', 3.83],
    content: '宏观经济过热，受稳健货币政策影\n响，余额宝收益率随之上升',
    lineLength: 50,
  },
];

export default class App extends React.Component {
  state = {
    data: [],
  };
  componentDidMount() {
    $.getJSON('/assets/data/income.json', data => {
      this.setState({
        data,
      });
    });
  }
  render() {
    const { data } = this.state;
    return (
      <Chart forceFit height={440} data={data} scale={scale} padding={[50]}>
        <Tooltip />
        <Axis />
        <Line position="time*rate" />
        {guides.map((opts: any, i: number) => {
          return <Guide key={i} {...opts} />;
        })}
      </Chart>
    );
  }
}

```
