### ISSUE TITLE
怎样在viser-vue怎么vue 中注册主题配置？

### ISSUE THREAD

**Issue by fengbindev** [viserjs/viser#364]
theme
类型：? string;
描述：主题，目前支持 'default'、'dark' , 可采用注册的方式注册新主题

**Comment by huxiaoyun** [comment]
@kinghoo

**Comment by kinghoo5201** [comment]
写了个例子你看一下@fengbindev https://codepen.io/kinghoo5201/pen/pBYwao?editors=1000
