### ISSUE TITLE
为什么bizcharts中的onGetG2Instance在viser没有，这边遇到了一个问题

### ISSUE THREAD

**Issue by dawven** [viserjs/viser#366]
图表更新数据时并没有加载动画，在bizcharts关联的issues问题一模一样是[传送门](https://github.com/alibaba/BizCharts/issues/412)

**Comment by huxiaoyun** [comment]
并没有暴露这个 api 。尽量用 react 自己的更新机制来重绘组件啊。

**Comment by dawven** [comment]
> 并没有暴露这个 api 。尽量用 react 自己的更新机制来重绘组件啊。

好的，感谢回复

**Comment by kinghoo5201** [comment]
可以更新chart的key来强制重新渲染

**Comment by dawven** [comment]
![](http://ww1.sinaimg.cn/thumbnail/007mpDP6gy1g2qa881vvug324c0taqva.gif)
