### ISSUE TITLE
Viser-Vue guide和series的属性vStyle在tsx/jsx中会被认为是Vue Directives,有没有必要换一个参数名?

### ISSUE THREAD

**Issue by xxbld** [viserjs/viser#374]
// style会被认为是css属性
// vXXX会被编译成vue 指令
const jsx=(<Com style={} vAAA={}/>) //error
const jsx=(<Com {...{props:{style:{},vAAA:{}}}}/>) //correct

**Comment by huxiaoyun** [comment]
api 不会随便更换哦~ 考虑会大版本更新做兼容。

**Comment by wangshaoan** [comment]
yuque的api都有问题
