### ISSUE TITLE
水波图 vue版本的代码不显示了  我写入项目也是不显示

### ISSUE THREAD

**Issue by SentiyWhen** [viserjs/viser#378]
<img width="1313" alt="WechatIMG11" src="https://user-images.githubusercontent.com/12071454/58526529-ce589200-8201-11e9-95cb-183692b60ff2.png">

**Comment by huxiaoyun** [comment]
田老板麻烦看下~

**Comment by LighterEast** [comment]
vue 的 v-guide中position属性改为下图
![image](https://user-images.githubusercontent.com/32625695/59437942-1c39e080-8e25-11e9-8335-ff06dd0062e0.png)，data中的pos删掉

**Comment by huxiaoyun** [comment]
https://viserjs.gitee.io/demo.html#/viser/others/liquid-fill-gauge
