### ISSUE TITLE
Axis 设置 label 不生效

### ISSUE THREAD

**Issue by axuebin** [viserjs/viser#379]
### 版本

"viser-react": "^2.4.6"

### code
```
import { Axis } from 'viser-react';
const label = {
  density: 3,
  autoRotate: true,
  textStyle: {
    fill: '#ff5151'
  }
};
<Axis label={label}/>
```

### 效果

![image](https://user-images.githubusercontent.com/13316392/58772534-10ac1580-85ec-11e9-8ece-d60cb9abf7a8.png)

### 期待效果

轴上的刻度文字可以根据个数和宽度自适应

**Comment by huxiaoyun** [comment]
https://www.yuque.com/rs385i/yzbt72/ecacgz#label

density 0~1 哈

**Comment by F-loat** [comment]
配置 label 貌似必须先配置 Axis 的 dataKey 才会生效
