### ISSUE TITLE
横轴显示不全

### ISSUE THREAD

**Issue by 806549997** [viserjs/viser#383]
```
import { Chart, Tooltip, Axis, Line, Point } from 'viser-react';
import * as React from 'react';

const data = [
  { year: '1991-1-1', value: 3 },
  { year: '1992-1-1', value: 4 },
  { year: '1993-1-1', value: 3.5 },

  { year: '1996-1-1', value: 6 },
  { year: '1997-2-2', value: 7 },
  { year: '1998-3-3', value: 9 },
  { year: '1999-4-4', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
}];


export default class App extends React.Component {
  render() {
    return (
      <Chart forceFit height={400} data={data} scale={scale}>
        <Tooltip />
        <Axis />
        <Line position="year*value" />
        <Point position="year*value" shape="circle"/>
      </Chart>
    );
  }
}
```
这种日期，横轴会显示不出来
![image](https://user-images.githubusercontent.com/17961751/59323343-e30e4d00-8d0c-11e9-95a9-1eb88ad61b9a.png)

**Comment by huxiaoyun** [comment]
```
import { Chart, Tooltip, Axis, Line, Point } from 'viser-react';
import * as React from 'react';

const data = [
  { year: '1991-1-1', value: 3 },
  { year: '1992-1-1', value: 4 },
  { year: '1993-1-1', value: 3.5 },

  { year: '1996-1-1', value: 6 },
  { year: '1997-2-2', value: 7 },
  { year: '1998-3-3', value: 9 },
  { year: '1999-4-4', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  type: 'cat',   // 设置为分类格式
}];


export default class App extends React.Component {
  render() {
    return (
      <Chart forceFit height={400} data={data} scale={scale}>
        <Tooltip />
        <Axis />
        <Line position="year*value" />
        <Point position="year*value" shape="circle"/>
      </Chart>
    );
  }
}

```
![image](https://user-images.githubusercontent.com/4345248/59436187-b26c0780-8e21-11e9-84b9-694fd20a643a.png)

**Comment by 806549997** [comment]
> ```
> import { Chart, Tooltip, Axis, Line, Point } from 'viser-react';
> import * as React from 'react';
> 
> const data = [
>   { year: '1991-1-1', value: 3 },
>   { year: '1992-1-1', value: 4 },
>   { year: '1993-1-1', value: 3.5 },
> 
>   { year: '1996-1-1', value: 6 },
>   { year: '1997-2-2', value: 7 },
>   { year: '1998-3-3', value: 9 },
>   { year: '1999-4-4', value: 13 },
> ];
> 
> const scale = [{
>   dataKey: 'value',
>   min: 0,
> },{
>   dataKey: 'year',
>   type: 'cat',   // 设置为分类格式
> }];
> 
> 
> export default class App extends React.Component {
>   render() {
>     return (
>       <Chart forceFit height={400} data={data} scale={scale}>
>         <Tooltip />
>         <Axis />
>         <Line position="year*value" />
>         <Point position="year*value" shape="circle"/>
>       </Chart>
>     );
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/4345248/59436187-b26c0780-8e21-11e9-84b9-694fd20a643a.png)

感谢
