### ISSUE TITLE
The geographical location does not match the map of autonavi

### ISSUE THREAD

**Issue by langlangbody** [viserjs/viser#384]
**viser demo**
![image](https://user-images.githubusercontent.com/39820299/59492364-6372b080-8ebb-11e9-978d-a336daa4f8a8.png)

**高德demo**

![image](https://user-images.githubusercontent.com/39820299/59492503-b0ef1d80-8ebb-11e9-8c19-172cfad5b5bf.png)

When I used type: GeoJSON as the template to draw a regional map, the map I drew deviated from the geographical location of the case in the autonavi map API . How do you adjust the geographical areas drawn in viser to match those in autonavi

**Comment by huxiaoyun** [comment]
pls give an online demo
