### ISSUE TITLE
页面有点击事件时视图叠加

### ISSUE THREAD

**Issue by yinfoyuan** [viserjs/viser#385]
![{94DDDD92-EE9E-4AC1-AEDE-6233468EFC4A}_20190614202716](https://user-images.githubusercontent.com/35027364/59509191-f246f380-8ee2-11e9-961e-85eae2c0bff8.jpg)
![{06775FF1-3795-4B9C-94E1-549A4858B03C}_20190614202732](https://user-images.githubusercontent.com/35027364/59509192-f246f380-8ee2-11e9-9156-b85c5a3e6747.jpg)

**Comment by huxiaoyun** [comment]
give an online demo ， thank u
