### ISSUE TITLE
词云的color属性没有用

### ISSUE THREAD

**Issue by yemubing** [viserjs/viser#388]
词云设置color，但是字体的颜色不会改变。viser-vue官网的例子的颜色也只有一种

**Comment by yemubing** [comment]
求大佬解答，

**Comment by reg01** [comment]
同求，业务上遇到这个问题了

**Comment by yemubing** [comment]
后面我的解决方案是在mounted的时候直接操作dom元素的。

**Comment by microacup** [comment]
同样的问题。

**Comment by microacup** [comment]
配置顺序问题，参考https://github.com/antvis/G2/issues/1060；
