### ISSUE TITLE
How to hide gridlines

### ISSUE THREAD

**Issue by imanhodjaev** [viserjs/viser#389]
Hi,

Thanks for your efforts and time!
I've been trying to hide gridlines on area chart tried to set `:grid="null"` set `dataKey` etc. but they didn't work either.

```html
<v-axis :dataKey="value" :grid="null" :show="false"/>
```

This is what I have
<img width="444" alt="Screenshot 2019-06-25 at 14 06 20" src="https://user-images.githubusercontent.com/354868/60096906-81110700-9752-11e9-9092-ad07f1ffe906.png">

This is what I've been trying to achieve
<img width="300" alt="Screenshot 2019-06-25 at 16 55 12" src="https://user-images.githubusercontent.com/354868/60109118-12d83e80-976a-11e9-9cac-d7282fd59ab6.png">

What is the proper way to hide gridlines, went through docs but was unable to find clean answers.

Thanks.

**Comment by huxiaoyun** [comment]
try
```
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip />
      <v-axis dataKey="value" :grid="grid"/>
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>
  </div>
</template>

<script>
const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  min: 0,
  max: 1,
}];

export default {
  data() {
    return {
      grid: null,
      data,
      scale,
      height: 400,
    };
  }
};
</script>

```
![image](https://user-images.githubusercontent.com/4345248/63415398-482e9f00-c430-11e9-85fd-cf8926dbb2d8.png)
