### ISSUE TITLE
[QA]怎么修改tooltip上那个小圆点呢？

### ISSUE THREAD

**Issue by djkloop** [viserjs/viser#396]
```
// @antv/data-set: "0.10.2"
// @viser-vue: "2.4.6"
```
![image](https://user-images.githubusercontent.com/21050914/61261680-2436c880-a7b5-11e9-88b1-5031d77ee851.png)

**Comment by AnonymousArthur** [comment]
同问，g2TooltipMarker属性貌似可以，但是没有Demo，文档也没写咋用。

**Comment by LighterEast** [comment]
可以使用tooltip中的itemTpl属性重写tooltip的内部结构，可以参考https://viserjs.gitee.io/demo.html#/viser/box/basic-box中的例子
