### ISSUE TITLE
viser-vue 色块图中文字显示控制?

### ISSUE THREAD

**Issue by sulin2018** [viserjs/viser#398]
![image](https://user-images.githubusercontent.com/11908337/61680639-f74a5e80-ad3c-11e9-905c-2615e8bccb57.png)
为什么示例代码`https://viserjs.github.io/demo.html#/viser/heatmap/color-box`中没有值显示在方块中, 我用我的数据渲染了就有值了 请问如何控制使其不显示值?

**Comment by huxiaoyun** [comment]
@田志东 ~

**Comment by LighterEast** [comment]
这里显示的值是由polygon中的label属性控制的，你可以试一下label={null}，相关文档https://www.yuque.com/rs385i/yzbt72/zrumt7
