### ISSUE TITLE
viser-vue 地图无数据时不显示问题

### ISSUE THREAD

**Issue by sulin2018** [viserjs/viser#399]
![image](https://user-images.githubusercontent.com/11908337/61854442-ad09de80-aef0-11e9-89d6-e0e46a1d6e11.png)
如图, 把模拟数据去掉不会显示地图. 能不能显示一个白色地图. 世界地图也是, 必须有数据才会渲染.

**Comment by huxiaoyun** [comment]
暂不支持。欢迎提 pr 。 需要修改 g2 底层代码
