### ISSUE TITLE
矩形树图的 tooltip 显示不完整

### ISSUE THREAD

**Issue by HaveF** [viserjs/viser#401]
[矩形树图](https://viserjs.github.io/demo.html#/viser/relation/treemap-diagram)

如下，浏览人数不显示
![image](https://user-images.githubusercontent.com/54462/63244183-4bd6f000-c28f-11e9-9758-a92a327022ae.png)

对照[G2 原版 矩形树图 - AntV](https://antv.alipay.com/zh-cn/g2/3.x/demo/relation/treemap.html)没找到问题在哪

**Comment by HaveF** [comment]
[fix a display bug of treemap-diagram by HaveF · Pull Request #111 · viserjs/viserjs.github.io](https://github.com/viserjs/viserjs.github.io/pull/111/files)

**Comment by w3313003** [comment]
把demo里的
```js
 const tooltip = ['name', (name, count) => ({ name, count })];
```
修改为
```js
 const tooltip = ['name*value', (name, count) => ({ name, count })];
```
