### ISSUE TITLE
分组柱状图怎么设置颜色渐变

### ISSUE THREAD

**Issue by shenqingqing** [viserjs/viser#403]
:color="['type','#0a62fc-#55fce2',]"

**Comment by huxiaoyun** [comment]
@LighterEast

**Comment by LighterEast** [comment]
:color="['type','#0a62fc-#55fce2',]" 中的'type'不是固定的，
比如你要展示的数据data格式为:
data=[{name:'aaa',value:10},{name:'bbb',value:20}],
那么color的配置为:
:color="['name','#0a62fc-#55fce2',]",
可以试一下看看

**Comment by Zuojiangtao** [comment]
> :color="['type','#0a62fc-#55fce2',]" 中的'type'不是固定的，
> 比如你要展示的数据data格式为:
> data=[{name:'aaa',value:10},{name:'bbb',value:20}],
> 那么color的配置为:
> :color="['name','#0a62fc-#55fce2',]",
> 可以试一下看看

![image](https://user-images.githubusercontent.com/22252182/69771985-a3a7c000-11c9-11ea-9934-986901adac9c.png)

----
这个是按照你的方式做出来的，我想要一个柱状图的颜色从上到下的渐变应该怎么弄呢？

----
这是代码：
````
 <v-bar position="month*Value" :color="['month', '#0C6FE1-#F65860']" />
````

**Comment by LazyLine** [comment]
有解决方案吗，我也遇到了这个问题

**Comment by LazyLine** [comment]
> > :color="['type','#0a62fc-#55fce2',]" 中的'type'不是固定的，
> > 比如你要展示的数据data格式为:
> > data=[{name:'aaa',value:10},{name:'bbb',value:20}],
> > 那么color的配置为:
> > :color="['name','#0a62fc-#55fce2',]",
> > 可以试一下看看
> 
> ![image](https://user-images.githubusercontent.com/22252182/69771985-a3a7c000-11c9-11ea-9934-986901adac9c.png)
> 
> 这个是按照你的方式做出来的，我想要一个柱状图的颜色从上到下的渐变应该怎么弄呢？
> 
> 这是代码：
> 
> ```
>  <v-bar position="month*Value" :color="['month', '#0C6FE1-#F65860']" />
> ```

**Comment by LazyLine** [comment]
有解决方案吗，我也遇到了这个问题，要一个柱状图的颜色从上到下的渐变
