### ISSUE TITLE
is:issue is:open 为什么通过script引用的vue-viser可以正常显示柱状图，但不能显示环形图啊，var ViserVue = window.ViserVue.default      Vue.use(ViserVue);     真是很无语啊

### ISSUE THREAD

**Issue by wangjingithub** [viserjs/viser#405]
is:issue is:open 为什么通过script引用的vue-viser可以正常显示柱状图，但不能显示环形图啊，var ViserVue = window.ViserVue.default      Vue.use(ViserVue);     真是很无语啊
<v-chart :force-fit="true" :height="height" renderer="svg">
			  <v-tooltip ></v-tooltip>
			  <v-axis></v-axis>
			  <v-legend></v-legend>
			  <v-view :data="data" :scale="scale" :filter="filter">
			    <v-stack-bar :position="'year*percent'" :color="'country'" :v-style="stackBarStyle"></v-stack-bar>
			  </v-view>
			</v-chart>这种可以显示

<v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip :showTitle="false" dataKey="item*percent" />
      <v-axis />
      <v-legend dataKey="item" />
      <v-pie
        position="percent"
        color="item"
        :vStyle="pieStyle"
        :label="labelConfig"
      />
      <v-coord type="theta" />
    </v-chart>这种就不行了。。。。。

**Comment by wangjingithub** [comment]
viser通过script引用，怎样使用viser案例中的vue代码啊，为什么不显示啊

**Comment by huxiaoyun** [comment]
有在线案例吗？
