### ISSUE TITLE
React tooltip position fixed y-axis middle of current x position.

### ISSUE THREAD

**Issue by electic** [viserjs/viser#407]
Is it possible to adjust the tooltip so it is always in the middle of the current position?

<img width="645" alt="Screen Shot 2019-09-12 at 11 30 25 PM" src="https://user-images.githubusercontent.com/43028/64841905-57c78080-d5b5-11e9-8076-429e2d58f057.png">

The tooltip would move at some fixed position on the y axis and move horizontally on the x-axis as the mouse moves. When it reaches each end, it would move to not flow outside of the chart like so:

<img width="907" alt="Screen Shot 2019-09-12 at 11 31 49 PM" src="https://user-images.githubusercontent.com/43028/64841971-86455b80-d5b5-11e9-9978-4aaca974e8c2.png">

Any help appreciated!

**Comment by aisykost** [comment]
On the same issue above - is the "offset" property supposed to control that behavior? Setting it, however, does not seem to make any difference in the tooltip's position. For instance, in the example here - https://viserjs.gitee.io/demo.html#/viser/others/cutomize-tooltip, changing the offset does not have any impact on the tooltip.

Looking forward to hearing back!
Thanks!
