### ISSUE TITLE
viser-vue，v-chart 添加key之后， 重新设置 data 属性后 当前点击的图例颜色重置 不能手动设置

### ISSUE THREAD

**Issue by zzzz-Z** [viserjs/viser#408]
当前点击的图例需要改变颜色 
给chart 为了解决重复点击加上key之后 
点击图例 更新其他页面上图例的数据 
当前图例也会触发更新 颜色重置  手动设置的颜色失效
[复现地址](https://codesandbox.io/s/vue-template-i5y4o)

**Comment by huxiaoyun** [comment]
第二个图表的key 为什么要设置成 new Date().getTime() 呢？

设置成固定的 key 就不会触发更新了。

key 变化，重绘，这个是正常的吧
