### ISSUE TITLE
曲线面积图怎么设置颜色渐变

### ISSUE THREAD

**Issue by Zuojiangtao** [viserjs/viser#411]
![image](https://user-images.githubusercontent.com/22252182/66732983-8e343c00-ee90-11e9-9abc-6b1f8e20d6d8.png)

就是这种效果，在单个曲线面积图中的颜色设置为渐变

**Comment by leepule** [comment]
https://doc.vux.li/zh-CN/components/v-chart.html
可以去这看    不过也不多

**Comment by Zuojiangtao** [comment]
> https://doc.vux.li/zh-CN/components/v-chart.html
> 可以去这看 不过也不多

这个是vux的，我是直接用的viser-vue,不知道有没有暴露的可更改的参数，我是没找到，如果不行就只能换插件了

**Comment by huxiaoyun** [comment]
https://github.com/viserjs/viser/issues/403  参考下这个issue

**Comment by Zuojiangtao** [comment]
> #403 参考下这个issue

试了，没有用
