### ISSUE TITLE
Async data cause duplicate chart rendering

### ISSUE THREAD

**Issue by evilucifero** [viserjs/viser#42]
When chart get data asynchronously, it seems render twice.

See demo: 
https://viserjs.github.io/demo.html?type=point&example=scatter
https://viserjs.github.io/demo.html?type=point&example=scatter-series

But ```adjust="jitter"``` will fixed this problem, it's confused.

See demo: 
https://viserjs.github.io/demo.html?type=point&example=jitter

**Comment by arcthur** [comment]
already fixed
