### ISSUE TITLE
ant-design-vue 下forceFit失效

### ISSUE THREAD

**Issue by tkokto** [viserjs/viser#421]
ant-design-vue 引入 vue-grid-layout组件

`<grid-layout
        :layout.sync="layout"
        :col-num="24"
        :row-height="30"
        :is-draggable="true"
        :is-resizable="true"
        :is-mirrored="false"
        :vertical-compact="true"
        :margin="[10, 10]" >

        <grid-item
          @click="openWidgetSetting"
          v-for="item in layout"
          :x="item.x"
          :y="item.y"
          :w="item.w"
          :h="item.h"
          :i="item.i"
          :key="item.i"
          :isResizable="true"
          @resize="resizeEvent"
          @resized="resizedEvent">
          <component :is="item.type" :heights="item.height" :widths="item.width" :ref="'widget'+item.i"></component>

        </grid-item>
      </grid-layout>`
使用动态组件引入viser图表组件，组件设置属性forceFit=true，发现占满整个屏幕

**Comment by huxiaoyun** [comment]
有传递width  height 吗？

**Comment by tkokto** [comment]
不好意思，height 400，width 不用传，使用forceFit

**Comment by tkokto** [comment]
> 有传递width height 吗？给个完整demo吧

不好意思，height 400，width 不用传，使用forceFit
