### ISSUE TITLE
viser如何获取原生的forceFit方法

### ISSUE THREAD

**Issue by zjq97** [viserjs/viser#431]

**Comment by huxiaoyun** [comment]
是获取实例的forceFit ???  forceFit 参数不能满足需求？？

**Comment by zjq97** [comment]
切换路由并改变窗口大小会造成图表模糊。g2官方文档是有一个forceFit方法，不是forceFit属性。属性是生效的。我需要这个方法来重新计算canvas的宽度

**Comment by zjq97** [comment]
切换路由并改变窗口大小会造成图表模糊。g2官方文档是有一个forceFit方法，不是forceFit属性。属性是生效的。我需要这个方法来重新计算canvas的宽度

> 是获取实例的forceFit ??? forceFit 参数不能满足需求？？

切换路由并改变窗口大小会造成图表模糊。g2官方文档是有一个forceFit方法，不是forceFit属性。属性是生效的。我需要这个方法来重新计算canvas的宽度

**Comment by zjq97** [comment]
> 是获取实例的forceFit ??? forceFit 参数不能满足需求？？

切换路由并改变窗口大小会造成图表模糊。g2官方文档是有一个forceFit方法，不是forceFit属性。属性是生效的。我需要这个方法来重新计算canvas的宽度

**Comment by huxiaoyun** [comment]
那就是需要chart 实例调用 forceFit 方法？

**Comment by zjq97** [comment]
> 那就是需要chart 实例调用 forceFit 方法？

是的

**Comment by MiaoJianxue** [comment]
viser要怎么去拿到这个chart实例呢？
