### ISSUE TITLE
angular 8.1.3 打开lvy后，启动错误

### ISSUE THREAD

**Issue by faner11** [viserjs/viser#435]
ERROR in There is no typings path for Chart in /Users/zzx/Documents/work/admin_project/node_modules/viser-ng/es/Chart.js.

We need to add an export for this class to a .d.ts typings file because Angular compiler needs to be able to reference this class in compiled code, such as templates.

The simplest fix for this is to ensure that this class is exported from the package's entry-point.

这是报错信息；

**Comment by huxiaoyun** [comment]
能给个完整的最简单的demo吗？

**Comment by faner11** [comment]
## 重现步骤
```
# 安装ng 8.1.3
ng new g2-demo 
# 安装 viser-ng
npm install viser-ng
```
```json
# tscinfig.json
# angularCompilerOptions 中设置 enableIvy 选项
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": true
  }
```
```
# angualr.json
# 默认aot编译
{
  "projects": {
    "my-existing-project": {
      "architect": {
        "build": {
          "options": {
            ...
            "aot": true,
          }
        }
      }
    }
  }
}
```
