### ISSUE TITLE
刻度线显示有问题，请帮忙分析下

### ISSUE THREAD

**Issue by m1655280161** [viserjs/viser#441]
![image](https://user-images.githubusercontent.com/40781133/69125302-7c256900-0ae0-11ea-8190-fb1689f40531.png)

**Comment by m1655280161** [comment]
刻度线展示有问题，fileds值同右侧红色框线里的值相同，但页面展示X轴多了几个时间，代码里也设置了:forceFit="true"的属性

**Comment by huxiaoyun** [comment]
看着感觉没错呀。你如果要严格按照你自己的数据来展示，设置下type:cate

**Comment by m1655280161** [comment]
刻度线没在正中央，如按照type:cate来设置，图例会显示在一起，成为一个大柱

**Comment by huxiaoyun** [comment]
给个完整demo吧

**Comment by m1655280161** [comment]
<template>
  <div>
    <v-chart
      :force-fit="true"
      :height="height"
      :scale="scale"
      :data="data_nd"
    >
      <v-tooltip />
      <v-axis />
      <v-legend />
      <v-line position="month*监测值" color="sbbm" />
      <v-point position="month*监测值" color="sbbm" :size="4" :v-style="style" :shape="'circle'" />
    </v-chart>
  </div>
</template>

<script>
const DataSet = require('@antv/data-set')
const scale = [{
  dataKey: 'month'
}]
export default {
  data () {
    return {
      height: 600,
      scale: scale,
      style: { stroke: '#fff', lineWidth: 1 },
    }
  }, 
  async created () {
    let params = { 
      xxxx: this._moment(new Date() - 24 * 60 * 60 * 1000 * 30),
      xxxx: this._moment(),
      xxxx:20 ,
      xxxx: 30
    }
    this.$store.commit('test/searchParams',params)
    this.$store.dispatch('test/getZhexian')
  },
  computed: {
    data_nd () {
      const tubiao_data = this.$store.state.test.zhexianData
      return this.getChartData(tubiao_data)
    }
  },
  methods: {
    getChartData: function(res) {
      if (res && res.data && res.data.length > 0) {
        let {data, dateList, sbmcList, message} = res
        const dv = new DataSet.View().source(data)
        dv.transform({
          type: 'fold',
          fields: sbmcList,
          key: 'sbbm',
          value: '监测值'
        })
        return dv.rows
      }else {
        // this.$message.error("暂无图表数据。")
        return []
      }
    }
  }
}
</script>

**Comment by m1655280161** [comment]
```
<template>
  <div>
    <v-chart 
      :forceFit="true" 
      :height="height" 
      :data="data_nd"
    >
      <v-tooltip />
      <v-axis />
      <v-legend />
      <v-stack-bar position="时间*监测值" color="sbbm" />
    </v-chart>
  </div>
</template>

<script>
const DataSet = require('@antv/data-set')
export default {
  data () {
    return {
      height:600,
    }
  },
  async created () {
    let params = { 
      xxxx: '',
      xxxx: '',
    }
     this.$store.commit('test/searchParams',params)
    this.$store.dispatch('test/getZhutuData')
  },
   computed: {
    data_nd() {
      const tubiao_data = this.$store.state.test.zhutuData
      return this.getChartData(tubiao_data)
    }
  },
  methods: {
    getChartData: function(res) {
      if (res && res.data && res.data.length > 0) {
        let {data, dateList, sbmcList, message} = res
        const dv = new DataSet.View().source(data)
        dv.transform({
          type: 'fold',
          fields: dateList,
          key: '时间',
          value: '监测值'
        })
        return dv.rows
      }else {
        return []
      }
    }
  }
}
</script>
```

**Comment by huxiaoyun** [comment]
@lightEast

**Comment by LighterEast** [comment]
chart上配置scale，
<v-chart :forceFit="true" :height="height" :data="data_nd" :scale="scale">
其中scale内容
scale: [{
          dataKey:'时间',
          type: 'timeCat'
        }]

**Comment by m1655280161** [comment]
问题已解决，谢谢！
