### ISSUE TITLE
viser-vue 中 使用htmlContent自定义v-tooltip后 没有鼠标跟随

### ISSUE THREAD

**Issue by moxuanluo** [viserjs/viser#444]

**Comment by moxuanluo** [comment]
<v-chart :forceFit="true" height="200" :data="data" padding="auto">
   <v-tooltip :follow="true" :htmlContent="htmlContent"></v-tooltip>
   <v-coord type="theta" :radius="0.75" />
   <v-stack-bar position="value" :color="color" :style="style" :label="label" />
</v-chart>


htmlContent: function htmlContent(title, items) {
        return (
          '<div class="g2-tooltip">' +
          '<div class="g2-tooltip-title" style="margin-bottom: 4px;"></div>' +
          '<ul class="g2-tooltip-list">' +
          "<li data-index={index}>" +
          '<span style="background-color:{color};width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>' +
          "{name}: {value}" +
          "</li>" +
          "</ul>" +
          "</div>"
        );
      }

使用了默认的模板 完全没有改动，生成图形后， tooltip并不能跟随鼠标移动，反而会固定到图形底部，
而https://viserjs.github.io/demo.html#/viser/components/tooltip-htmlcontent 例子中，同样使用htmlContent自定义v-tooltip后  实现了 tooltip的鼠标跟随，
请问 htmlContent自定义v-tooltip后，怎样才能实现tooltip的鼠标跟随

**Comment by cuteCloud** [comment]
请问解决了吗

**Comment by hanfengv** [comment]
样式问题: 

<style>
.custom-tooltip {
  position: absolute;
}
</style>
