### ISSUE TITLE
Is there any way to see tag document about viser-vue ? thanks.

### ISSUE THREAD

**Issue by sherry0429** [viserjs/viser#447]
I read G2 document and all usage like :
```javascript
const chart = ...
chart.render()
```

But viser-vue usage like:
```html
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip :showTitle="false" dataKey="item*percent" />
      <v-axis />
      <v-legend dataKey="item" />
      <v-pie position="percent" color="item" :v-style="pieStyle" :label="labelConfig" />
      <v-coord type="theta" />
    </v-chart>
  </div>
</template>
```

So I find two versions about use this repo, HTML tags or JavaScripts, Now my question is where could I find a document about v-* tags about viser-vue? 

for example, now I know v-pie is a pie graph, and what tag about a single line graph ? is there any documentation to read? 

Thanks.

**Comment by ABoat365** [comment]
you see see you,look this[line](https://viserjs.gitee.io/demo.html#/viser/line/basic-line)

**Comment by huxiaoyun** [comment]
> @sherry0429 you see see you,look this [line](https://viserjs.gitee.io/demo.html#/viser/line/basic-line)

wow ....   thank u for response.

u see see u , very chinglish ~~ emmm ~  interesting ~

**Comment by sherry0429** [comment]
six six six @ABoat365
