### ISSUE TITLE
bug: getDataView should check data is Null

### ISSUE THREAD

**Issue by huxiaoyun** [viserjs/viser#45]
CommonDataSet.prototype.getDataView = function (data, dataView) {
        if (dataView === void 0) { dataView = 'rows'; }
        if (__WEBPACK_IMPORTED_MODULE_0_lodash__["isArray"](dataView) && dataView.length >= 2) {
            var type = dataView[0];
            if (__WEBPACK_IMPORTED_MODULE_0_lodash__["isFunction"](dataView[1])) {
                if (type === 'nodes') {
                    return dataView[1](data.getAllNodes());
                }
                else if (type === 'edges') {
                    return dataView[1](data.getAllLinks());
                }
            }
        }
        return data[dataView];    // when data=[] , it will occure bug
    };

**Comment by evilucifero** [comment]
same as #57
