### ISSUE TITLE
viser-vue的v-axis组件的label支持不支持直接使用htmlTemplate进行渲染？

### ISSUE THREAD

**Issue by zkwolf** [viserjs/viser#450]
如题，搜了一下api好像没有对应的api来实现

**Comment by huxiaoyun** [comment]
支持的~ 马上发个版本。

**Comment by huxiaoyun** [comment]
https://www.yuque.com/rs385i/yzbt72/ecacgz#jz23l     api 定义

**Comment by zkwolf** [comment]
好的，谢谢，顺便问一下viser这边有固定的版本更新周期吗
