### ISSUE TITLE
对比漏斗图的显示问题

### ISSUE THREAD

**Issue by VXiaoXin** [viserjs/viser#452]
### 1.正常情况：
数据：
```json
// 预期数据
const expectData = [
  {value: 100, name: '展现'},
  {value: 80, name: '点击'},
  {value: 60, name: '访问'},
  {value: 40, name: '咨询'},
  {value: 30, name: '订单'}
];
// 实际数据
const actualData = [
  {value: 80, name: '展现'},
  {value: 50, name: '点击'},
  {value: 30, name: '访问'},
  {value: 10, name: '咨询'},
  {value: 5, name: '订单'},
];
```
效果：
![image](https://user-images.githubusercontent.com/42163284/71499336-02308e80-289b-11ea-8097-e3a72beb75ef.png)

### 2.异常情况
数据：
```json
// 预期数据
const expectData = [
  {value: 100, name: '展现'},
  {value: 80, name: '点击'},
  {value: 60, name: '访问'},
  {value: 40, name: '咨询'},
  {value: 30, name: '订单'},
];
// 实际数据
const actualData = [
  {value: 80, name: '展现'},
  {value: 80, name: '点击'},
  {value: 50, name: '访问'},
  {value: 50, name: '咨询'},
  {value: 5, name: '订单'},
];
```
效果：
![image](https://user-images.githubusercontent.com/42163284/71499353-0e1c5080-289b-11ea-8888-fbdd43cd2fd7.png)

> 这个时候的实际数据还是小于逾期数据的，但是这个显示感觉很不对。

**Comment by huxiaoyun** [comment]
没搞明白。。请附上完整demo

**Comment by VXiaoXin** [comment]
就是在官网上面把上面那些参数，赋值粘贴进去就可以看到这些问题了。
问题主要是上面的数据比下面的数据要小，但是上面的面积却比下面的面积要大。
貌似antV也是这样，所以我觉得应该是antV的问题。

**Comment by huxiaoyun** [comment]
需要理解漏斗图的画图原理哈，梯形的上下边是两个数据。
![image](https://user-images.githubusercontent.com/4345248/79709089-d9258500-82f3-11ea-8d9d-ffdcaab3ff46.png)


像你这种情况，不建议使用漏斗图了，因为图形会覆盖，建议用条形图来查看漏斗。
![image](https://user-images.githubusercontent.com/4345248/79709138-f4909000-82f3-11ea-852e-e0415a7b305a.png)

https://viserjs.gitee.io/demo.html#/viser/bar/grouped-bar
