### ISSUE TITLE
仪表盘不能在 div 中剧中显示

### ISSUE THREAD

**Issue by flutterWang** [viserjs/viser#456]
![7C69FB47-0C14-47F7-925B-13C43274BDE9](https://user-images.githubusercontent.com/54163491/72366126-a0927000-3734-11ea-9396-82d4cd398a56.png)
![2B89F7F2-28CB-4465-B6B2-B678889D7BC6](https://user-images.githubusercontent.com/54163491/72366109-940e1780-3734-11ea-84ce-f347652ff6bf.png)

**Comment by huxiaoyun** [comment]
请附上demo
