### ISSUE TITLE
求助，v-point 的 shape没有效果 angular中

### ISSUE THREAD

**Issue by vickmeng** [viserjs/viser#46]
<div>
        <v-chart [forceFit]="forceFit" [height]="height" [data]="data" [scale]="scale">
          <v-tooltip></v-tooltip>
          <v-axis></v-axis>
          <v-line  position="year*value"></v-line>
          <v-point shape="diamond" size="10" color="red" position="year*value"></v-point>//shape 不好使
        </v-chart>
      </div>

**Comment by evilucifero** [comment]
Thanks for reporting problem. Would you like to paste a piece of code here ?

**Comment by zoukanghua** [comment]
在vue中实现带图片遮罩的词云时，自定义了shape，传入v-point中，shape没起作用
<v-point :position="'x*y'" :color="'text'" :shape="'cloud'" />

import { registerShape } from 'viser-vue';
function getTextAttrs(cfg) {
    return Object.assign({}, {
        fillOpacity: cfg.opacity,
        fontSize: cfg.origin._origin.size,
        rotate: cfg.origin._origin.rotate,
        text: cfg.origin._origin.text,
        textAlign: 'center',
        fontFamily: cfg.origin._origin.font,
        fill: cfg.color,
        textBaseline: 'Alphabetic'
      }, cfg.style);
  }

registerShape('point', 'cloud', {
      draw(cfg, container) {
        const attrs = getTextAttrs(cfg);
        return container.addShape('text', {
          attrs: Object.assign(attrs, {
              x: cfg.x,
              y: cfg.y
            })
        });
     }
    });
