### ISSUE TITLE
词云在safari浏览器上不显示

### ISSUE THREAD

**Issue by Jerry99** [viserjs/viser#461]
词云为什么在safari浏览器上不显示，有哪位大神能帮忙解决一下吗

**Comment by huxiaoyun** [comment]
![image](https://user-images.githubusercontent.com/4345248/76922884-eaeac580-690c-11ea-8a80-3991a9e8ecd4.png)
![image](https://user-images.githubusercontent.com/4345248/76922896-ef16e300-690c-11ea-867b-f1d1d05d519c.png)
![image](https://user-images.githubusercontent.com/4345248/76922902-f3430080-690c-11ea-828b-d3785818dfc9.png)


demo正常哦
