### ISSUE TITLE
Show dataKey in Tooltip item

### ISSUE THREAD

**Issue by larissa-n** [viserjs/viser#469]
The tooltop customization options seem to be limited to {name}:{value}, where {name} is bound to the x data label (see example: https://viserjs.github.io/demo.html#/viser/others/column-error).

<img width="237" alt="Screen Shot 2020-03-04 at 11 56 28 AM" src="https://user-images.githubusercontent.com/37840830/75872896-4a29df80-5e0f-11ea-8ebf-07911f341717.png">

I can't seem to access y data labels, e.g. the dataKey attribute names (in this example: value, range) as item labels.

**Comment by huxiaoyun** [comment]
if u want to custom tooltip totally, use this demo
https://viserjs.gitee.io/demo.html#/viser/components/tooltip-customized

containerTpl  、 itemTpl  api only support name and value
