### ISSUE TITLE
官方实例 <v-tooltip showTitle="false" 依然显示title angular中

### ISSUE THREAD

**Issue by tk231321** [viserjs/viser#47]
http://antv.alipay.com/zh-cn/g2/3.x/demo/pie/multi-level.html

**Comment by evilucifero** [comment]
Thanks for reporting bug. We've already confirmed and fixed it. 👍

**Comment by evilucifero** [comment]
Now you can see demo from below.

[https://viserjs.github.io/demo.html?type=pie&example=multi-level-pie](https://viserjs.github.io/demo.html?type=pie&example=multi-level-pie)
