### ISSUE TITLE
用svg渲染图表，切换页面，再返回后，js报错

### ISSUE THREAD

**Issue by xagpx** [viserjs/viser#474]
![image](https://user-images.githubusercontent.com/13012069/76236104-25969300-6267-11ea-9fca-cc7a0b81c55f.png)
![image](https://user-images.githubusercontent.com/13012069/76236289-6b535b80-6267-11ea-93ec-aa8347d8c701.png)

用svg渲染图表，切换页面，再返回后，js报错
renderer='svg'

**Comment by huxiaoyun** [comment]
麻烦提供下完成的demo

**Comment by MiaoJianxue** [comment]
我也遇到 了这个问题，没有设置图表宽度，用的forceFIt为true，宽度继承父元素的宽度，手动伸缩图表，为了让图表手动自适应，我就写了个手动触发window.resize事件的方法，就报这个错误了
