### ISSUE TITLE
如何在不重新加载整个网页的情况下刷新viser angular组件来呈现图表。

### ISSUE THREAD

**Issue by knight3340019** [viserjs/viser#478]
如何在不重新加载整个网页的情况下刷新viser angular组件来呈现图表。
我们使用了2个标签，一个用于用户数据输入，另一个标签用于生成配置的图表。
在第一个标签中，我们获取图表数据以呈现图表。
用户输入数据后，图表不会立即在“图表”标签中呈现，而是要发生一个事件（刷新网页或者缩放网页）后才会呈现图表。
如果我们将相同的数据存储在数据库中，并将相同的数据发送到网页上的“图表”标签以加载，他将会渲染。
需要一个不重新加载网页来呈现图表的解决方案。

**Comment by huxiaoyun** [comment]
使用key的机制吧~
