### ISSUE TITLE
What's the necessity of viser?

### ISSUE THREAD

**Issue by NoraGithub** [viserjs/viser#48]
As its API is the same as G2, and what I should do is to read G2 doc, so why should I use it ?
I am using vue and in my opinion, it would just make my project more complex and hope to get your idea.
Do you mean that the tags like `<v-chart>` would be convenient for us?

**Comment by evilucifero** [comment]
In opinion, semantic component what described as the tags like ```<v-chart>```, can make your code more clearly, especially in visualization development. It can vividly express all element on the chart.

Secondly, Viser's abstraction like ```<v-line />``` makes you more easily to draw a line chart. Demos are here: [https://viserjs.github.io/demo.html](https://viserjs.github.io/demo.html)

Thanks for using Viser :-)
