### ISSUE TITLE
radar 雷达图如何实现下图效果？

### ISSUE THREAD

**Issue by meguoe** [viserjs/viser#480]
请大神不吝赐教!!!!!!!(下图为百度echarts效果)
<img width="626" alt="6C4470CA-F100-4E56-B359-33F180CA2CEA" src="https://user-images.githubusercontent.com/45955794/79305096-49fc2400-7f25-11ea-9cc2-60b93f6af87f.png">

**Comment by huxiaoyun** [comment]
差异点在哪里呢？

**Comment by meguoe** [comment]
> 差异点在哪里呢？
viser创建出来的radar图表tooltip信息如下，只会显示当前某个item的值
![image](https://user-images.githubusercontent.com/45955794/79943621-e1202900-849b-11ea-9eba-9f7ddc234de0.png)

**Comment by wht300** [comment]
可以试试[自定义Tooltip](https://viserjs.gitee.io/demo.html#/viser/components/tooltip-customized)，应该可以实现
