### ISSUE TITLE
一条数据是绘制图表出错

### ISSUE THREAD

**Issue by wangning1314** [viserjs/viser#492]
![微信图片_20200530155258](https://user-images.githubusercontent.com/22077957/83322891-b04ac500-a28d-11ea-8f95-19cf13f36c37.png)
当折线图只有一个数据时，没有绘制出point的点，而且在鼠标移动时，控制台报g2中的错误：Cannot read property 'draw' of undefined；
当有两条数据时，则没有问题了

**Comment by banboluli** [comment]
你解决了么，我也遇到同样问题了

**Comment by wangning1314** [comment]
Viser依赖的g2版本自动升级了，由原来的3.3.0变成了3.5.11，修改回去就好了

**Comment by wangning1314** [comment]
> 你解决了么，我也遇到同样问题了

Viser依赖的g2版本自动升级了，由原来的3.3.0变成了3.5.11，修改回去就好了
