### ISSUE TITLE
viser怎么调用forceFit方法，我手动伸缩图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表宽度才会自适应变化

### ISSUE THREAD

**Issue by MiaoJianxue** [viserjs/viser#543]
viser怎么调用forceFit方法，我手动伸缩图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表宽度才会自适应变化

**Comment by MiaoJianxue** [comment]
这个问题已解决

**Comment by JalenTang** [comment]
老哥 你是怎么解决的

**Comment by JalenTang** [comment]
> viser怎么调用forceFit方法，我手动伸缩图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表宽度才会自适应变化

老哥 你怎么解决的

**Comment by MiaoJianxue** [comment]
> > viser怎么调用forceFit方法，我手动扩展图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表横跨才会适应变化
> 
> 老哥你怎么解决的

在组件上写一个ref="splineChart",再mounted生命周期拿到chart实例，触发forceFit()方法，this.$ref.splineChart.chart.chartInstance.forceFit(),手动伸缩图表的时候，在手动触发这个方法就可以了，或者手动触发window窗口resize事件

**Comment by JalenTang** [comment]
> > > viser怎么调用forceFit方法，我手动扩展图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表横跨才会适应变化
> > 
> > 
> > 老哥你怎么解决的
> 
> 在组件上写一个ref="splineChart",再mounted生命周期拿到chart实例，触发forceFit()方法，this.$ref.splineChart.chart.chartInstance.forceFit(),手动伸缩图表的时候，在手动触发这个方法就可以了，或者手动触发window窗口resize事件

谢谢老哥

**Comment by MiaoJianxue** [comment]
> > > > viser怎么调用forceFit方法，我手动扩展图表的时候，怎么让图表自适应变化，现在只有窗口变了，图表横跨才会适应变化
> > > 
> > > 
> > > 老哥你怎么解决的
> > 
> > 
> > 在组件上写一个ref="splineChart",再mounted生命周期拿到chart实例，触发forceFit()方法，this.$ref.splineChart.chart.chartInstance.forceFit(),手动伸缩图表的时候，在手动触发这个方法就可以了，或者手动触发window窗口resize事件
> 
> 谢谢老哥
本人妹子一枚，我还小，哈哈哈哈
