### ISSUE TITLE
分组条形图：如何起别名才能让数据不被覆盖

### ISSUE THREAD

**Issue by JAVPHP** [viserjs/viser#569]
`<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data">
      <v-coord type="rect"  />
      <v-tooltip />
      <v-legend />
      <v-axis dataKey="value" position="right" />
      <v-axis dataKey="label" :label="label" />
      <v-bar position="label*value" color="type" :adjust="adjust" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { label: 'Mon.', userId1: 2800, userId2: 2260, userId3: 4000 },
    { label: 'Tues.', userId1: 1800, userId2: 1300 },
    { label: 'Wed.', userId1: 950, userId2: 900 },
    { label: 'Thur.', userId1: 500, userId2: 390 },
    { label: 'Fri.', userId1: 170, userId2: 100 },
  ];

  const dv = new DataSet.View().source(sourceData);

  dv.transform({
        type: 'rename',
        map: {
          'userId1': '张三',
          'userId2': '李四',
          'userId3': '张三'
        }
  })

  dv.transform({
    type: 'fold',
    fields: ['张三', '李四','张三'],
    key: 'type',
    value: 'value',
  });

  const data = dv.rows;

  const label = { offset: 12 };
  const adjust = [{ type: 'dodge', marginRatio: 1 / 32 }];

  export default {
    data() {
      return {
        data,
        height: 400,
        label: label,
        adjust: adjust,
      };
    }
  };
</script>`
![image](https://user-images.githubusercontent.com/48326762/119431238-cb3b0280-bd44-11eb-998e-e3342cc5dbce.png)

**Comment by JAVPHP** [comment]
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data">
      <v-coord type="rect"  />
      <v-tooltip />
      <v-legend />
      <v-axis dataKey="value" position="right" />
      <v-axis dataKey="label" :label="label" />
      <v-bar position="label*value" color="type" :adjust="adjust" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { label: 'Mon.', userId1: 2800, userId2: 2260, userId3: 4000 },
    { label: 'Tues.', userId1: 1800, userId2: 1300 },
    { label: 'Wed.', userId1: 950, userId2: 900 },
    { label: 'Thur.', userId1: 500, userId2: 390 },
    { label: 'Fri.', userId1: 170, userId2: 100 },
  ];

  const dv = new DataSet.View().source(sourceData);

  dv.transform({
        type: 'rename',
        map: {
          'userId1': '张三',
          'userId2': '李四',
          'userId3': '张三'
        }
  })


  dv.transform({
    type: 'fold',
    fields: ['张三', '李四','张三'],
    key: 'type',
    value: 'value',
  });



  const data = dv.rows;

  const label = { offset: 12 };
  const adjust = [{ type: 'dodge', marginRatio: 1 / 32 }];

  export default {
    data() {
      return {
        data,
        height: 400,
        label: label,
        adjust: adjust,
      };
    }
  };
</script>

**Comment by JAVPHP** [comment]
...html

<template>
  <div>
    <v-chart :force-fit="true" :height="height" :data="data" :scale="scale">
      <v-tooltip :on-show="onTooltipShow" :on-hide="onTooltipHide" :on-change="onTooltipChange"></v-tooltip>
      <v-axis></v-axis>
      <v-stack-bar :position="'year*percent'" :color="'country'" :v-style="stackBarStyle"></v-stack-bar>
    </v-chart>
  </div>
</template>

<script>
const DataSet = require('@antv/data-set');

const ds = new DataSet();
const dv = ds.createView().source(data);

dv.transform({
  type: 'percent',
  field: 'value',
  dimension: 'country',
  groupBy: ['year'],
  as: 'percent'
});

const data = [
  { country: 'Europe', year: '1750', value: 163 },
  { country: 'Europe', year: '1800', value: 203 },
  { country: 'Europe', year: '1850', value: 276 },
  { country: 'Europe', year: '1900', value: 408 },
  { country: 'Europe', year: '1950', value: 547 },
  { country: 'Europe', year: '1999', value: 729 },
  { country: 'Europe', year: '2050', value: 628 },
  { country: 'Europe', year: '2100', value: 828 },
  { country: 'Asia', year: '1750', value: 502 },
  { country: 'Asia', year: '1800', value: 635 },
  { country: 'Asia', year: '1850', value: 809 },
  { country: 'Asia', year: '1900', value: 947 },
  { country: 'Asia', year: '1950', value: 1402 },
  { country: 'Asia', year: '1999', value: 3634 },
  { country: 'Asia', year: '2050', value: 5268 },
  { country: 'Asia', year: '2100', value: 7268 }
];

const scale = [{
  dataKey: 'percent',
  min: 0,
  formatter: '.2%',
}, {
  dataKey: 'year',
  type: 'timeCat',
  alias: '日期'
}];

export default {
  data() {
    return {
      data: dv.rows,
      scale,
      height: 400,
      stackBarStyle: {
        stroke: '#fff',
        lineWidth: 1
      },
    };
  }
};
</script>

**Comment by JAVPHP** [comment]
<details>
<summary>代码如下</summary>

```html
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data">
      <v-coord type="rect"  />
      <v-tooltip />
      <v-legend />
      <v-axis dataKey="value" position="right" />
      <v-axis dataKey="label" :label="label" />
      <v-bar position="label*value" color="type" :adjust="adjust" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { label: 'Mon.', userId1: 2800, userId2: 2260, userId3: 4000 },
    { label: 'Tues.', userId1: 1800, userId2: 1300 },
    { label: 'Wed.', userId1: 950, userId2: 900 },
    { label: 'Thur.', userId1: 500, userId2: 390 },
    { label: 'Fri.', userId1: 170, userId2: 100 },
  ];

  const dv = new DataSet.View().source(sourceData);

  dv.transform({
        type: 'rename',
        map: {
          'userId1': '张三',
          'userId2': '李四',
          'userId3': '张三'
        }
  })


  dv.transform({
    type: 'fold',
    fields: ['张三', '李四','张三'],
    key: 'type',
    value: 'value',
  });



  const data = dv.rows;

  const label = { offset: 12 };
  const adjust = [{ type: 'dodge', marginRatio: 1 / 32 }];

  export default {
    data() {
      return {
        data,
        height: 400,
        label: label,
        adjust: adjust,
      };
    }
  };
</script>
```
</details>

**Comment by JAVPHP** [comment]
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data">
      <v-coord type="rect"  />
      <v-tooltip />
      <v-legend />
      <v-axis dataKey="value" position="right" />
      <v-axis dataKey="label" :label="label" />
      <v-bar position="label*value" color="type" :adjust="adjust" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { label: 'Mon.', userId1: 2800, userId2: 2260, userId3: 4000 },
    { label: 'Tues.', userId1: 1800, userId2: 1300 },
    { label: 'Wed.', userId1: 950, userId2: 900 },
    { label: 'Thur.', userId1: 500, userId2: 390 },
    { label: 'Fri.', userId1: 170, userId2: 100 },
  ];

  const dv = new DataSet.View().source(sourceData);

  dv.transform({
        type: 'rename',
        map: {
          'userId1': '张三',
          'userId2': '李四',
          'userId3': '张三'
        }
  })


  dv.transform({
    type: 'fold',
    fields: ['张三', '李四','张三'],
    key: 'type',
    value: 'value',
  });



  const data = dv.rows;

  const label = { offset: 12 };
  const adjust = [{ type: 'dodge', marginRatio: 1 / 32 }];

  export default {
    data() {
      return {
        data,
        height: 400,
        label: label,
        adjust: adjust,
      };
    }
  };
</script>

**Comment by JAVPHP** [comment]
```html
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data">
      <v-coord type="rect"  />
      <v-tooltip />
      <v-legend />
      <v-axis dataKey="value" position="right" />
      <v-axis dataKey="label" :label="label" />
      <v-bar position="label*value" color="type" :adjust="adjust" />
    </v-chart>
  </div>
</template>

<script>
  const DataSet = require('@antv/data-set');

  const sourceData = [
    { label: 'Mon.', userId1: 2800, userId2: 2260, userId3: 4000 },
    { label: 'Tues.', userId1: 1800, userId2: 1300 },
    { label: 'Wed.', userId1: 950, userId2: 900 },
    { label: 'Thur.', userId1: 500, userId2: 390 },
    { label: 'Fri.', userId1: 170, userId2: 100 },
  ];

  const dv = new DataSet.View().source(sourceData);

  dv.transform({
        type: 'rename',
        map: {
          'userId1': '张三',
          'userId2': '李四',
          'userId3': '张三'
        }
  })


  dv.transform({
    type: 'fold',
    fields: ['张三', '李四','张三'],
    key: 'type',
    value: 'value',
  });



  const data = dv.rows;

  const label = { offset: 12 };
  const adjust = [{ type: 'dodge', marginRatio: 1 / 32 }];

  export default {
    data() {
      return {
        data,
        height: 400,
        label: label,
        adjust: adjust,
      };
    }
  };
</script>
```

**Comment by MiaoJianxue** [comment]
正常不会取一样的名字，这明显是三个分类啊，取一样的名字没有可比性啊

**Comment by JAVPHP** [comment]
> 正常不会取一样的名字，这明显是三个分类啊，取一样的名字没有可比性啊

有些数据按照人进行统计，难道他们重名了，我能怎么办

**Comment by JAVPHP** [comment]
但是我已经找到解决方案了

**Comment by JAVPHP** [comment]
```html
<template>
  <a-card style="height: 500px" :bordered="false" title="回款收入面板——按个人年度统计">
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale">
      <v-coord type="rect" />
      <v-tooltip/>
      <v-legend />
      <v-axis dataKey="value" position="left"/>
      <v-axis dataKey="receivePaymentTime" :label="label" />
      <v-bar position="receivePaymentTime*value" color="type" :adjust="adjust" />
    </v-chart>
  </a-card>
</template>

<script>
import { finReceivePaymentYearPerColAmount } from '@/api/modular/main/finReceivePayment/finReceivePaymentManage'

const DataSet = require('@antv/data-set')

export default {
  name: 'YearPerColAmount',
  data() {
    return {
      data: [],
      users: {},
      height: 400,
      label: {
        offset: 12

      },
      adjust: [{
        type: 'dodge',
        marginRatio: 1 / 32
      }],
      scale: [
        {
          dataKey: 'type',
          formatter: this.tFormatter
        }
      ]
    }
  },
  mounted() {
    finReceivePaymentYearPerColAmount().then(res => {
      const dv = new DataSet.View().source(res.data.rows)
      const fields = ['annualTotalColAmount']
      this.users = res.data.users
      for (const key in this.users) {
        if (this.users.hasOwnProperty(key)) {
          fields.push(key)
        }
      }
      // dv.transform({
      //   type: 'rename',
      //   map: {
      //     'annualTotalApprovedAmount': '东京',
      //     '1275735541155614721': '伦敦'
      //   }
      // })
      dv.transform({
        type: 'fold',
        fields: fields,
        key: 'type',
        value: 'value'
      })
      // dv.transform({
      //   type: 'filter',
      //   callback(row) {
      //     console.log(row)
      //     if (row.type === 'annualTotalApprovedAmount') {
      //       row.type = '年度商机成本'
      //     }
      //     return row
      //   }
      // })
      this.data = dv.rows
    })
  },
  methods: {
    tFormatter(val) {
      if (val === 'annualTotalColAmount') {
        return '总收入'
      } else {
        return this.users[val].name
      }
    }
  }
}
</script>

<style scoped>

</style>


```

**Comment by JAVPHP** [comment]
```html
scale: [
        {
          dataKey: 'type',
          formatter: this.tFormatter
        }
      ]
```
formatter可以解决
