### ISSUE TITLE
数据更新时报错Cannot read property 'rows' of undefined

### ISSUE THREAD

**Issue by CHAACC** [viserjs/viser#57]
![image](https://user-images.githubusercontent.com/21275141/34099776-73f1d4be-e41b-11e7-8fa7-da99e454b3a0.png)

**Comment by CHAACC** [comment]
就是说我想更新数据应该怎么做？react版的

**Comment by evilucifero** [comment]
Would you like to show your React component code here？Thanks~

**Comment by CHAACC** [comment]
export const BookingView = ({
    data
}) => {
   const chartOpt={
        height:230,
        padding:[ '20%','8%','30%', '13%' ],
        data:makeData(data),
        dataPre:{
            transform: {
                type: 'fold',
                fields: ['本月', '上月'],
                key: 'month',
                value: 'value',
            },
        },
        scale :[{
            dataKey: 'date',
            ticks:[ 1,5, 10,15, 20,25,30],
        }]
    }
    const axisOpt={
        dataKey:'value',
    }
    const tooltipOpt = {
        triggerOn: 'mousemove',
        crosshairs: {
            type: 'line'
        }
    }
    return (
        <div className={styles.chart}>

            <Chart forceFit {...chartOpt}>
                <Tooltip {...tooltipOpt}/>
                <Axis {...axisOpt}/>
                <Legend />
                <Line position="date*value" color="month" />
                <Point position="date*value" color="month" size={3} style={{ stroke: '#fff', lineWidth: 1 }} />
            </Chart>

        </div>
    )
}

当data变化时就报错了，貌似要用changeData(),但不知怎么用

**Comment by Evoque** [comment]
I find this work => `this.chartPie.chart.chartInstance.changeData(data);`  the `chartPie` is the `<Chart>`ref.
I think the `<Chart>` should handle the `handleData()`, not the way I found.

**Comment by evilucifero** [comment]
Seems there are some problems in data change, I'm tracking this problem.

@Evoque Thanks for your advice. Obviously, it's a temporary solution. After I fixed bugs in Viser, you don't need to manually trigger changeData().

**Comment by jiongjian** [comment]
同问ng版的更新数据重绘应该怎么做？

**Comment by jiongjian** [comment]
同问ng版的更新数据重绘应该怎么做？

**Comment by gabencui** [comment]
vue版也遇到了这个问题

**Comment by evilucifero** [comment]
Bug has been fixed. Now you don't need to do any action to change data. Just pass a new data to chart, no matter what kind of viser you are using. 

错误已被修复。 现在你不需要做任何行动来改变数据。 只需传递一个新的数据到图表，不管你使用的是什么样的viser。

@Evoque @CHAACC @jiongjian @gabencui
