### ISSUE TITLE
animation in Pie

### ISSUE THREAD

**Issue by Evoque** [viserjs/viser#58]

**Comment by Evoque** [comment]
I know the reason:  
      When I got new Data, and use 'changeData' to update <Chart>,  new layer about the new data is drawn, but the old layer is there too, just covered by the new layer, I think it is an stupid bug and I don't want to use it lib anymore.

**Comment by evilucifero** [comment]
Could you describe the problem more clearly?

**Comment by Evoque** [comment]
I have found why the bug is shown, I am trying to fix it, If don't work,  come here for help later.

**Comment by evilucifero** [comment]
Well~ Contact us anytime when you are confused in Viser. Thanks.
