### ISSUE TITLE
ERROR in Unexpected value 'Axis in /Users/Documents/dashboard/node_modules/viser-ng/src/components/index.ts' declared by the module 'ViserModule in /Users/Documents/dashboard/node_modules/viser-ng/src/module.ts'. Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by jiongjian** [viserjs/viser#68]
跑ng build --prod的时候报这个错，咋整？

**Comment by huxiaoyun** [comment]
can u give a more specific example ?

**Comment by evilucifero** [comment]
Due to the worksforme of this error, we have to close this issue right now.
Please contact us any time if the repetition of this error occurs. Thanks for supporting viser.
