### ISSUE TITLE
横轴时间如何正确显示柱状图

### ISSUE THREAD

**Issue by xueye515** [viserjs/viser#75]
图片试了多次没有上传上来，结果就是数据柱状图最左侧的柱子压住了y轴，特别是只有一个柱子的时候。
要怎么才能实现正常的柱状图显示，
想不明白，为什么横轴为时间时，柱状图显示不正常，了解到你们文档上自动给设置为连续的类型了。
我感觉应该在柱状图时，时间不应该自动给转换成连续型。
 设置类型‘timeCat’
const scale = {
      date: {
        type: 'timeCat',
        alias: '时间'
      }
    };

**Comment by evilucifero** [comment]
Would you like to set scale like the code below? Most of Viser's config use array-like style instead of object-like style.

```javascript
const scale = [
  {
    dataKey: 'date',
    type: 'timeCat',
    alias: '时间',
  }
];
```

**Comment by xueye515** [comment]
这样设置解决问题了，
viser有对应的文档吗？
开发过程中参考的g2的文档，g2文档中 scale 是通过object 形式设置的，
如果开发中设置方式有差异，希望出相关的文档。

**Comment by evilucifero** [comment]
I will add docs about this asap. Thanks for your suggestion.

**Comment by evilucifero** [comment]
We've add docs about this.

[https://viserjs.github.io/docs.html#/guide/feature](https://viserjs.github.io/docs.html#/guide/feature)

In section 'dataKey 字段映射'.
