### ISSUE TITLE
求助，如何在datapre中使用两次tranform？

### ISSUE THREAD

**Issue by vickmeng** [viserjs/viser#81]
我在G2中用了两次tranform，不知viser中如何写。还是我tranform使用的方法不对？
const data = [
    { month: 'Jan', Tokyo: 7.0,  London: 3.9 , shanghai:3.2,  dalian:13.2},
    { month: 'Feb', Tokyo: 6.9,  London: 4.2 , shanghai:3.3,  dalian:23.2},
    { month: 'Mar', Tokyo: 9.5,  London: 5.7 , shanghai:8.2,  dalian:31.2},
    { month: 'Apr', Tokyo: 14.5, London: 8.5 , shanghai:10.1, dalian:13.2},
    { month: 'May', Tokyo: 18.4, London: 11.9, shanghai:5.2,  dalian:13.2}
  ];
  const ds = new DataSet();
  const dv = ds.createView().source(data);
  dv.transform({
    type: 'fold',
    fields: [ 'Tokyo', 'London'], // 展开字段集
    key: '国外城市', // key字段
    value: '国外气温', // value字段
  });
  dv.transform({
    type: 'fold',
    fields: [ 'shanghai', 'dalian'], // 展开字段集
    key: '国内城市', // key字段
    value: '国内气温', // value字段
  });

**Comment by evilucifero** [comment]
Viser use array-like config, you may try the code below:
```javascript
const dataPre = [{
  type: 'fold',
  fields: [ 'Tokyo', 'London'], // 展开字段集
  key: '国外城市', // key字段
  value: '国外气温', // value字段
}, {
  type: 'fold',
  fields: [ 'shanghai', 'dalian'], // 展开字段集
  key: '国内城市', // key字段
  value: '国内气温', // value字段
}];
```

**Comment by evilucifero** [comment]
I hope that would help you.

**Comment by vickmeng** [comment]
really helpful，another question,how to define colors for lines in this chart like G2 ？
![image](https://user-images.githubusercontent.com/19486247/34754235-77730a5c-f5f7-11e7-97cc-c492dcac9a84.png)
![image](https://user-images.githubusercontent.com/19486247/34754268-a42fee3e-f5f7-11e7-9f68-39aed1d4d5a0.png)
![image](https://user-images.githubusercontent.com/19486247/34754278-b28e62b2-f5f7-11e7-84ac-46ef705f3978.png)

**Comment by evilucifero** [comment]
@vickmeng Firstly, we have just published viser 2.0. In viser 2.0, you can try to use DataSet outside the Chart, and you don't need to write `dataPre` any more. You can just use DataSet as G2's behavior.

The demo is updated here. [https://viserjs.github.io/demo.html#/bar/grouped-column](https://viserjs.github.io/demo.html#/bar/grouped-column)

**Comment by evilucifero** [comment]
@vickmeng Secondly, Color is also support complex properties.

Some demos here.

[https://viserjs.github.io/demo.html#/box/group-box](https://viserjs.github.io/demo.html#/box/group-box)

[https://viserjs.github.io/demo.html#/facet/mirror-facet](https://viserjs.github.io/demo.html#/facet/mirror-facet)

**Comment by evilucifero** [comment]
Thanks for using Viser！
