### ISSUE TITLE
Angular version fails the production build

### ISSUE THREAD

**Issue by agiledigits** [viserjs/viser#87]
Environment: Angular 5.0
Application: simple example like https://viserjs.github.io/demo.html#/bar/stacked-bar

Ran into this error:
$ ng build --prod
Date: 2018-01-10T01:47:26.232Z
Hash: 13c7cb86d7d449e7a853
Time: 3607ms
chunk {0} styles.9c0ad738f18adc3d19ed.bundle.css (styles) 79 bytes [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in : Unexpected value 'Axis in /xxxxx/viser-app/node_modules/viser-ng/src/components/index.ts' declared by the module 'ViserModule in /xxxxx/viser-app/node_modules/viser-ng/src/module.ts'. Please add a @Pipe/@Directive/@Component annotation.
node_modules/viser/src/utils/CustomizeUtils.ts(1,12): error TS2304: Cannot find name 'require'.
node_modules/viser/src/core/CommonDataSet.ts(4,17): error TS2304: Cannot find name 'require'.
node_modules/viser/src/core/CommonChart.ts(19,12): error TS2304: Cannot find name 'require'.
node_modules/viser/src/index.ts(16,12): error TS2304: Cannot find name 'require'.

**Comment by agiledigits** [comment]
@linhuiw With the demo app I'm still getting this error:
$ ng build --prod
Date: 2018-01-22T19:29:37.376Z
Hash: 5ffe57570d0b80e57423
Time: 3738ms
chunk {0} styles.9c0ad738f18adc3d19ed.bundle.css (styles) 79 bytes [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in : Unexpected value 'Axis in /xxxxx/viser-ng-demo/node_modules/viser-ng/src/components/index.ts' declared by the module 'ViserModule in /xxxxx/viser-ng-demo/node_modules/viser-ng/src/module.ts'. Please add a @Pipe/@Directive/@Component annotation.

I'm not sure why the build would go into "node_modules/viser-ng/src". The build works without the "--prod" switch.

My TypeScript version is 2.6.2.

**Comment by linhuiw** [comment]
It looks that in `Aot` mode , works error.

perhaps related to this issue https://github.com/angular/angular/issues/15890
Let me see how to fix it.
