### ISSUE TITLE
线性图设置别名问题 

### ISSUE THREAD

**Issue by Shruan** [viserjs/viser#89]
不改变数据源的情况下 修改下方显示的字段
![image](https://user-images.githubusercontent.com/28869029/34812224-beb24322-f6df-11e7-8080-ce0d7c5dcf1a.png)

**Comment by arcthur** [comment]
使用 data-set 的 rename 的 transform, https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_rename-%E5%AD%97%E6%AE%B5%E9%87%8D%E5%91%BD%E5%90%8D

**Comment by Shruan** [comment]
```
      <v-chart
        class="line-chart"
        :force-fit="true"
        :height="310"
        :data-set="dataSet"
        :data="reportData"
        :dataPre="lineDataPre"
        :scale="lineScale">
        <v-tooltip />
        <v-axis />
        <v-legend />
        <v-line
        :position="'xAxisNames*value'"
        :shape="'hv'"
        :color="'key'" />
      </v-chart>
```
### script
```
  lineDataPre: {
        transform: {
          type: 'fold',
          fields: ['allOrderValues', 'finishOrderValues'],
          key: 'key',
          value: 'value'
        }
      },
      lineScale: [
        {
          dataKey: 'xAxisNames',
          min: 0,
          max: 1
        }
      ],
      dataSet: {
        transform: {
          type: 'rename',
          map: {
            allOrderValues: '全部', // row.xxx 会被替换成 row.yyy
            finishOrderValues: '完成'
          }
        }
      }
```

**Comment by Shruan** [comment]
是这样么 ，但是没有效果

**Comment by Shruan** [comment]
没有尝试出来 ，可以出一个例子么

**Comment by arcthur** [comment]
不是，

transform: {
          type: 'fold',
          fields: ['allOrderValues', 'finishOrderValues'],
          key: 'key',
          value: 'value'
        }


这部分对应

const dv = new DataSet.View().source(sourceData);
dv.transform({
  type: 'fold',
  fields: ['allOrderValues', 'finishOrderValues'],
  key: 'key',
  value: 'value'
});
const data = dv.rows;

要改成这种写法，然后 data 传到 chart 的 data 中

**Comment by Shruan** [comment]
还是没有尝试出使用方法

**Comment by Shruan** [comment]
可以在vue实例文档里编写一个参考示例呢

**Comment by Shruan** [comment]
都么有人回的么 。。改成这种写法了 也是没有效果。
```
  const dv = new DataSet.View().source(this.reportData)
    dv.transform({
      type: 'fold',
      fields: ['allOrderValues', 'finishOrderValues'],
      key: 'key',
      value: 'value'
    })
    dv.transform({
      type: 'rename',
      map: {
        allOrderValues: '全部工单',
        finishOrderValues: '完成工单'
      }
    })
    console.log(dv)
    this.data = dv.rows
```
得到的数据是这样的并没有什么效果 
![image](https://user-images.githubusercontent.com/28869029/35855276-afa3070c-0b6d-11e8-9740-3c58b8ec093b.png)

官方又没有写文档， 不知道怎么解决，要不然这个双线图标没什么作用

能不能在图表示例里面出一个能够正常设置别名的例子？ ？？？？？？？？？？

**Comment by hxghost69** [comment]
想问下怎么issue怎么关闭了？解决方法到底是什么啊？

**Comment by JAVPHP** [comment]
我也想问这个别名的设置到底怎么设置
