### ISSUE TITLE
更新了viser2.0，，使用官网demo报错

### ISSUE THREAD

**Issue by ShawshankLin** [viserjs/viser#94]
![qq 20180112132701](https://user-images.githubusercontent.com/16248686/34861019-9ea5bbbe-f79c-11e7-83e2-212d24148cd7.png)

官网的demo
https://viserjs.github.io/demo.html#/line/basic-line

**Comment by evilucifero** [comment]
Thanks for reporting. We are fixing it right now.

**Comment by arcthur** [comment]
fix from 2.0.1
