### ISSUE TITLE
viser2.0新api使用方法疑问？

### ISSUE THREAD

**Issue by ShawshankLin** [viserjs/viser#96]
现在的api使用不是很懂，，感觉麻烦了很多了，，现在一定要从new DataSet.View().source传进数据源吗，，但是有些数据是从父组件传下来的，是传到props的，但是我怎么传给new DataSet.View().source，，，而不能像以前从v-chart 传入data了吗

**Comment by arcthur** [comment]
考虑到 data-set.js 非常大，也不是所有图表都需要，所有这次就剥离了。https://viserjs.github.io/docs.html#/guide/usage   这里可以看使用，data-set 部分可以看 g2 官网  https://antv.alipay.com/zh-cn/g2/3.x/tutorial/data-set.html

**Comment by ShawshankLin** [comment]
那我不能使用v-chart 的data绑定一个变量传入数据源吗，，一定要从new DataSet.View().source传进吗，但是created拿不到props的数据呢，，这个要怎么传？

**Comment by ShawshankLin** [comment]
我看折线图单线的demo是不用DataSet，双线就用到了DataSet，这个是必须的吗
