### ISSUE TITLE
如何实现组合图？

### ISSUE THREAD

**Issue by zl612** [viserjs/viser#99]
问下如果想把柱状图和折线图放一起怎么弄出来？  有demo吗？  请告诉我下  如有发链接会更好

**Comment by evilucifero** [comment]
https://viserjs.github.io/demo.html#/stock/stock-and-area

Maybe you can read the code of this demo. Stock chart contains area/line/candle. You can compose bar and line like this.

Hope useful for you.

**Comment by zl612** [comment]
Thank you

**Comment by ShawshankLin** [comment]
@evilucifero viser的双轴图标https://viserjs.github.io/demo.html#/viser/others/double-axes，，如果要往左轴再加一条线，，怎么加呢？
